//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAAmlEnquiryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Master : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRPRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLNTRSKINDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLTTWOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPRFDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPRFNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INCPRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISSUEAUTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REASONCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESNDESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZAGEPRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZFORMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZFOTOINDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZFOTOPRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZPANCOPYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZPANIDNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRPRF {
            get {
                return this.ADDRPRFField;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRPRFField, value) != true)) {
                    this.ADDRPRFField = value;
                    this.RaisePropertyChanged("ADDRPRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLNTRSKIND {
            get {
                return this.CLNTRSKINDField;
            }
            set {
                if ((object.ReferenceEquals(this.CLNTRSKINDField, value) != true)) {
                    this.CLNTRSKINDField = value;
                    this.RaisePropertyChanged("CLNTRSKIND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLTNAME {
            get {
                return this.CLTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLTNAMEField, value) != true)) {
                    this.CLTNAMEField = value;
                    this.RaisePropertyChanged("CLTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLTTWO {
            get {
                return this.CLTTWOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLTTWOField, value) != true)) {
                    this.CLTTWOField = value;
                    this.RaisePropertyChanged("CLTTWO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPRF {
            get {
                return this.IDPRFField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPRFField, value) != true)) {
                    this.IDPRFField = value;
                    this.RaisePropertyChanged("IDPRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPRFDT {
            get {
                return this.IDPRFDTField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPRFDTField, value) != true)) {
                    this.IDPRFDTField = value;
                    this.RaisePropertyChanged("IDPRFDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPRFNUM {
            get {
                return this.IDPRFNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPRFNUMField, value) != true)) {
                    this.IDPRFNUMField = value;
                    this.RaisePropertyChanged("IDPRFNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INCPRF {
            get {
                return this.INCPRFField;
            }
            set {
                if ((object.ReferenceEquals(this.INCPRFField, value) != true)) {
                    this.INCPRFField = value;
                    this.RaisePropertyChanged("INCPRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISSUEAUTH {
            get {
                return this.ISSUEAUTHField;
            }
            set {
                if ((object.ReferenceEquals(this.ISSUEAUTHField, value) != true)) {
                    this.ISSUEAUTHField = value;
                    this.RaisePropertyChanged("ISSUEAUTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REASONCD {
            get {
                return this.REASONCDField;
            }
            set {
                if ((object.ReferenceEquals(this.REASONCDField, value) != true)) {
                    this.REASONCDField = value;
                    this.RaisePropertyChanged("REASONCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESNDESC {
            get {
                return this.RESNDESCField;
            }
            set {
                if ((object.ReferenceEquals(this.RESNDESCField, value) != true)) {
                    this.RESNDESCField = value;
                    this.RaisePropertyChanged("RESNDESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZAGEPRF {
            get {
                return this.ZAGEPRFField;
            }
            set {
                if ((object.ReferenceEquals(this.ZAGEPRFField, value) != true)) {
                    this.ZAGEPRFField = value;
                    this.RaisePropertyChanged("ZAGEPRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZFORM {
            get {
                return this.ZFORMField;
            }
            set {
                if ((object.ReferenceEquals(this.ZFORMField, value) != true)) {
                    this.ZFORMField = value;
                    this.RaisePropertyChanged("ZFORM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZFOTOIND {
            get {
                return this.ZFOTOINDField;
            }
            set {
                if ((object.ReferenceEquals(this.ZFOTOINDField, value) != true)) {
                    this.ZFOTOINDField = value;
                    this.RaisePropertyChanged("ZFOTOIND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZFOTOPRF {
            get {
                return this.ZFOTOPRFField;
            }
            set {
                if ((object.ReferenceEquals(this.ZFOTOPRFField, value) != true)) {
                    this.ZFOTOPRFField = value;
                    this.RaisePropertyChanged("ZFOTOPRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZPANCOPY {
            get {
                return this.ZPANCOPYField;
            }
            set {
                if ((object.ReferenceEquals(this.ZPANCOPYField, value) != true)) {
                    this.ZPANCOPYField = value;
                    this.RaisePropertyChanged("ZPANCOPY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZPANIDNO {
            get {
                return this.ZPANIDNOField;
            }
            set {
                if ((object.ReferenceEquals(this.ZPANIDNOField, value) != true)) {
                    this.ZPANIDNOField = value;
                    this.RaisePropertyChanged("ZPANIDNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAAmlEnquiryService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AMLEnquiry", ReplyAction="http://tempuri.org/IService/AMLEnquiryResponse")]
        UWSaralServices.LAAmlEnquiryService.Master AMLEnquiry(string CltID, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AMLEnquiry", ReplyAction="http://tempuri.org/IService/AMLEnquiryResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAAmlEnquiryService.Master> AMLEnquiryAsync(string CltID, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LAAmlEnquiryService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LAAmlEnquiryService.IService>, UWSaralServices.LAAmlEnquiryService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LAAmlEnquiryService.Master AMLEnquiry(string CltID, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.AMLEnquiry(CltID, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAAmlEnquiryService.Master> AMLEnquiryAsync(string CltID, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.AMLEnquiryAsync(CltID, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
