//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAServiceTiffConversion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAServiceTiffConversion.TiffConverterServiceSoap")]
    public interface TiffConverterServiceSoap {
        
        // CODEGEN: Generating message contract since element name strFileExtension from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTiffBytes", ReplyAction="*")]
        UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse GetTiffBytes(UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTiffBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse> GetTiffBytesAsync(UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiffBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiffBytes", Namespace="http://tempuri.org/", Order=0)]
        public UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequestBody Body;
        
        public GetTiffBytesRequest() {
        }
        
        public GetTiffBytesRequest(UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTiffBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFileExtension;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] arrFileBytes;
        
        public GetTiffBytesRequestBody() {
        }
        
        public GetTiffBytesRequestBody(string strFileExtension, byte[] arrFileBytes) {
            this.strFileExtension = strFileExtension;
            this.arrFileBytes = arrFileBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiffBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiffBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponseBody Body;
        
        public GetTiffBytesResponse() {
        }
        
        public GetTiffBytesResponse(UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTiffBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytesResult;
        
        public GetTiffBytesResponseBody() {
        }
        
        public GetTiffBytesResponseBody(UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytesResult) {
            this.GetTiffBytesResult = GetTiffBytesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiffConverterServiceSoapChannel : UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiffConverterServiceSoapClient : System.ServiceModel.ClientBase<UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap>, UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap {
        
        public TiffConverterServiceSoapClient() {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiffConverterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap.GetTiffBytes(UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest request) {
            return base.Channel.GetTiffBytes(request);
        }
        
        public UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytes(string strFileExtension, byte[] arrFileBytes) {
            UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest inValue = new UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest();
            inValue.Body = new UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequestBody();
            inValue.Body.strFileExtension = strFileExtension;
            inValue.Body.arrFileBytes = arrFileBytes;
            UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse retVal = ((UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap)(this)).GetTiffBytes(inValue);
            return retVal.Body.GetTiffBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse> UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap.GetTiffBytesAsync(UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest request) {
            return base.Channel.GetTiffBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAServiceTiffConversion.GetTiffBytesResponse> GetTiffBytesAsync(string strFileExtension, byte[] arrFileBytes) {
            UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest inValue = new UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequest();
            inValue.Body = new UWSaralServices.LAServiceTiffConversion.GetTiffBytesRequestBody();
            inValue.Body.strFileExtension = strFileExtension;
            inValue.Body.arrFileBytes = arrFileBytes;
            return ((UWSaralServices.LAServiceTiffConversion.TiffConverterServiceSoap)(this)).GetTiffBytesAsync(inValue);
        }
    }
}
