//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.esbSendSMSSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.futuregenerali.in/FGSMSServiceBPMIntf", ConfigurationName="esbSendSMSSvc.FGSMSServiceBPMIntf")]
    public interface FGSMSServiceBPMIntf {
        
        // CODEGEN: Generating message contract since the operation sendSMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UWSaralServices.esbSendSMSSvc.sendSMSResponse1 sendSMS(UWSaralServices.esbSendSMSSvc.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UWSaralServices.esbSendSMSSvc.sendSMSResponse1> sendSMSAsync(UWSaralServices.esbSendSMSSvc.sendSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.futuregenerali.in/FGSMSServiceBPMIntf")]
    public partial class sendSMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textMsgField;
        
        private string toNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string textMsg {
            get {
                return this.textMsgField;
            }
            set {
                this.textMsgField = value;
                this.RaisePropertyChanged("textMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string toNumber {
            get {
                return this.toNumberField;
            }
            set {
                this.toNumberField = value;
                this.RaisePropertyChanged("toNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.futuregenerali.in/life")]
    public partial class LF_ExceptionDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool errorFlagField;
        
        private bool errorFlagFieldSpecified;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool errorFlag {
            get {
                return this.errorFlagField;
            }
            set {
                this.errorFlagField = value;
                this.RaisePropertyChanged("errorFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorFlagSpecified {
            get {
                return this.errorFlagFieldSpecified;
            }
            set {
                this.errorFlagFieldSpecified = value;
                this.RaisePropertyChanged("errorFlagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.futuregenerali.in/FGSMSServiceBPMIntf")]
    public partial class sendSMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LF_ExceptionDetail faultResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public LF_ExceptionDetail faultResponse {
            get {
                return this.faultResponseField;
            }
            set {
                this.faultResponseField = value;
                this.RaisePropertyChanged("faultResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.futuregenerali.in/FGSMSServiceBPMIntf", Order=0)]
        public UWSaralServices.esbSendSMSSvc.sendSMS sendSMS;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(UWSaralServices.esbSendSMSSvc.sendSMS sendSMS) {
            this.sendSMS = sendSMS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.futuregenerali.in/FGSMSServiceBPMIntf", Order=0)]
        public UWSaralServices.esbSendSMSSvc.sendSMSResponse sendSMSResponse;
        
        public sendSMSResponse1() {
        }
        
        public sendSMSResponse1(UWSaralServices.esbSendSMSSvc.sendSMSResponse sendSMSResponse) {
            this.sendSMSResponse = sendSMSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FGSMSServiceBPMIntfChannel : UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FGSMSServiceBPMIntfClient : System.ServiceModel.ClientBase<UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf>, UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf {
        
        public FGSMSServiceBPMIntfClient() {
        }
        
        public FGSMSServiceBPMIntfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FGSMSServiceBPMIntfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FGSMSServiceBPMIntfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FGSMSServiceBPMIntfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UWSaralServices.esbSendSMSSvc.sendSMSResponse1 UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf.sendSMS(UWSaralServices.esbSendSMSSvc.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public UWSaralServices.esbSendSMSSvc.sendSMSResponse sendSMS(UWSaralServices.esbSendSMSSvc.sendSMS sendSMS1) {
            UWSaralServices.esbSendSMSSvc.sendSMSRequest inValue = new UWSaralServices.esbSendSMSSvc.sendSMSRequest();
            inValue.sendSMS = sendSMS1;
            UWSaralServices.esbSendSMSSvc.sendSMSResponse1 retVal = ((UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf)(this)).sendSMS(inValue);
            return retVal.sendSMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWSaralServices.esbSendSMSSvc.sendSMSResponse1> UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf.sendSMSAsync(UWSaralServices.esbSendSMSSvc.sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.esbSendSMSSvc.sendSMSResponse1> sendSMSAsync(UWSaralServices.esbSendSMSSvc.sendSMS sendSMS) {
            UWSaralServices.esbSendSMSSvc.sendSMSRequest inValue = new UWSaralServices.esbSendSMSSvc.sendSMSRequest();
            inValue.sendSMS = sendSMS;
            return ((UWSaralServices.esbSendSMSSvc.FGSMSServiceBPMIntf)(this)).sendSMSAsync(inValue);
        }
    }
}
