//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LABankEnquiry {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterCorporateClient", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterCorporateClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRDESC01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRDESC02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRDESC03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRDESC04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRDESC05Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRDESC01 {
            get {
                return this.ADDRDESC01Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRDESC01Field, value) != true)) {
                    this.ADDRDESC01Field = value;
                    this.RaisePropertyChanged("ADDRDESC01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRDESC02 {
            get {
                return this.ADDRDESC02Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRDESC02Field, value) != true)) {
                    this.ADDRDESC02Field = value;
                    this.RaisePropertyChanged("ADDRDESC02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRDESC03 {
            get {
                return this.ADDRDESC03Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRDESC03Field, value) != true)) {
                    this.ADDRDESC03Field = value;
                    this.RaisePropertyChanged("ADDRDESC03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRDESC04 {
            get {
                return this.ADDRDESC04Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRDESC04Field, value) != true)) {
                    this.ADDRDESC04Field = value;
                    this.RaisePropertyChanged("ADDRDESC04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRDESC05 {
            get {
                return this.ADDRDESC05Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRDESC05Field, value) != true)) {
                    this.ADDRDESC05Field = value;
                    this.RaisePropertyChanged("ADDRDESC05");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPersonalClient", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterPersonalClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLTDOBXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLTDOBX {
            get {
                return this.CLTDOBXField;
            }
            set {
                if ((object.ReferenceEquals(this.CLTDOBXField, value) != true)) {
                    this.CLTDOBXField = value;
                    this.RaisePropertyChanged("CLTDOBX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterClientBankAccCreate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterClientBankAccCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BNKACTYPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLNTSELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACOUNT {
            get {
                return this.BANKACOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACOUNTField, value) != true)) {
                    this.BANKACOUNTField = value;
                    this.RaisePropertyChanged("BANKACOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKKEY {
            get {
                return this.BANKKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKKEYField, value) != true)) {
                    this.BANKKEYField = value;
                    this.RaisePropertyChanged("BANKKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BNKACTYP {
            get {
                return this.BNKACTYPField;
            }
            set {
                if ((object.ReferenceEquals(this.BNKACTYPField, value) != true)) {
                    this.BNKACTYPField = value;
                    this.RaisePropertyChanged("BNKACTYP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLNTSEL {
            get {
                return this.CLNTSELField;
            }
            set {
                if ((object.ReferenceEquals(this.CLNTSELField, value) != true)) {
                    this.CLNTSELField = value;
                    this.RaisePropertyChanged("CLNTSEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterClientBankAccEnquiry", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterClientBankAccEnquiry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACCDSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BNKACTYPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CURRCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATEFROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FACTHOUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCTYCDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACCDSC {
            get {
                return this.BANKACCDSCField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACCDSCField, value) != true)) {
                    this.BANKACCDSCField = value;
                    this.RaisePropertyChanged("BANKACCDSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACOUNT {
            get {
                return this.BANKACOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACOUNTField, value) != true)) {
                    this.BANKACOUNTField = value;
                    this.RaisePropertyChanged("BANKACOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKKEY {
            get {
                return this.BANKKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKKEYField, value) != true)) {
                    this.BANKKEYField = value;
                    this.RaisePropertyChanged("BANKKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BNKACTYP {
            get {
                return this.BNKACTYPField;
            }
            set {
                if ((object.ReferenceEquals(this.BNKACTYPField, value) != true)) {
                    this.BNKACTYPField = value;
                    this.RaisePropertyChanged("BNKACTYP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURRCODE {
            get {
                return this.CURRCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CURRCODEField, value) != true)) {
                    this.CURRCODEField = value;
                    this.RaisePropertyChanged("CURRCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATEFROM {
            get {
                return this.DATEFROMField;
            }
            set {
                if ((object.ReferenceEquals(this.DATEFROMField, value) != true)) {
                    this.DATEFROMField = value;
                    this.RaisePropertyChanged("DATEFROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATTO {
            get {
                return this.DATTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DATTOField, value) != true)) {
                    this.DATTOField = value;
                    this.RaisePropertyChanged("DATTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACTHOUS {
            get {
                return this.FACTHOUSField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTHOUSField, value) != true)) {
                    this.FACTHOUSField = value;
                    this.RaisePropertyChanged("FACTHOUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SCTYCDE {
            get {
                return this.SCTYCDEField;
            }
            set {
                if ((object.ReferenceEquals(this.SCTYCDEField, value) != true)) {
                    this.SCTYCDEField = value;
                    this.RaisePropertyChanged("SCTYCDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterClientBankAccUpdate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterClientBankAccUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BNKACTYPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLNTSELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACOUNT {
            get {
                return this.BANKACOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACOUNTField, value) != true)) {
                    this.BANKACOUNTField = value;
                    this.RaisePropertyChanged("BANKACOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKKEY {
            get {
                return this.BANKKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKKEYField, value) != true)) {
                    this.BANKKEYField = value;
                    this.RaisePropertyChanged("BANKKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BNKACTYP {
            get {
                return this.BNKACTYPField;
            }
            set {
                if ((object.ReferenceEquals(this.BNKACTYPField, value) != true)) {
                    this.BNKACTYPField = value;
                    this.RaisePropertyChanged("BNKACTYP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLNTSEL {
            get {
                return this.CLNTSELField;
            }
            set {
                if ((object.ReferenceEquals(this.CLNTSELField, value) != true)) {
                    this.CLNTSELField = value;
                    this.RaisePropertyChanged("CLNTSEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LABankEnquiry.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLIUPC", ReplyAction="http://tempuri.org/IService/CLIUPCResponse")]
        UWSaralServices.LABankEnquiry.MasterCorporateClient CLIUPC(
                    string CLTTWO, 
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECURITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLIUPC", ReplyAction="http://tempuri.org/IService/CLIUPCResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterCorporateClient> CLIUPCAsync(
                    string CLTTWO, 
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECURITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLIUPP", ReplyAction="http://tempuri.org/IService/CLIUPPResponse")]
        UWSaralServices.LABankEnquiry.MasterPersonalClient CLIUPP(
                    string CLTTWO, 
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLIUPP", ReplyAction="http://tempuri.org/IService/CLIUPPResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterPersonalClient> CLIUPPAsync(
                    string CLTTWO, 
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBACRT", ReplyAction="http://tempuri.org/IService/CBACRTResponse")]
        UWSaralServices.LABankEnquiry.MasterClientBankAccCreate CBACRT(string CBANKSEL, string BANKACCDSC, string BANKACOUNT, string BANKKEY, string BNKACTYP, string CURRCODE, string DATEFROM, string FACTHOUS, string SCTYCDE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBACRT", ReplyAction="http://tempuri.org/IService/CBACRTResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccCreate> CBACRTAsync(string CBANKSEL, string BANKACCDSC, string BANKACOUNT, string BANKKEY, string BNKACTYP, string CURRCODE, string DATEFROM, string FACTHOUS, string SCTYCDE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBAENQ", ReplyAction="http://tempuri.org/IService/CBAENQResponse")]
        UWSaralServices.LABankEnquiry.MasterClientBankAccEnquiry CBAENQ(string CBANKSEL, string BANKACOUNT, string BANKKEY, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBAENQ", ReplyAction="http://tempuri.org/IService/CBAENQResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccEnquiry> CBAENQAsync(string CBANKSEL, string BANKACOUNT, string BANKKEY, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBAUPD", ReplyAction="http://tempuri.org/IService/CBAUPDResponse")]
        UWSaralServices.LABankEnquiry.MasterClientBankAccUpdate CBAUPD(
                    string CBANKSEL, 
                    string BANKACCDSC, 
                    string BANKACOUNT, 
                    string BANKKEY, 
                    string BNKACTYP, 
                    string CURRCODE, 
                    string DATEFROM, 
                    string DATTO, 
                    string FACTHOUS, 
                    string SCTYCDE, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CBAUPD", ReplyAction="http://tempuri.org/IService/CBAUPDResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccUpdate> CBAUPDAsync(
                    string CBANKSEL, 
                    string BANKACCDSC, 
                    string BANKACOUNT, 
                    string BANKKEY, 
                    string BNKACTYP, 
                    string CURRCODE, 
                    string DATEFROM, 
                    string DATTO, 
                    string FACTHOUS, 
                    string SCTYCDE, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LABankEnquiry.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LABankEnquiry.IService>, UWSaralServices.LABankEnquiry.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LABankEnquiry.MasterCorporateClient CLIUPC(
                    string CLTTWO, 
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECURITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLIUPC(CLTTWO, CAPITAL, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSTAT, CTRYCODE, CTRYORIG, DIRMAIL, ECACT, FAO, FAXNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, SECURITYNO, SERVBRH, SRDATE, STAFFNO, STATCODE, TAXFLAG, TGRAM, TLXNO, VIP, OLDIDNO, RINTERNET, RTAXIDNUM, ZSPECIND, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterCorporateClient> CLIUPCAsync(
                    string CLTTWO, 
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECURITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLIUPCAsync(CLTTWO, CAPITAL, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSTAT, CTRYCODE, CTRYORIG, DIRMAIL, ECACT, FAO, FAXNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, SECURITYNO, SERVBRH, SRDATE, STAFFNO, STATCODE, TAXFLAG, TGRAM, TLXNO, VIP, OLDIDNO, RINTERNET, RTAXIDNUM, ZSPECIND, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LABankEnquiry.MasterPersonalClient CLIUPP(
                    string CLTTWO, 
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLIUPP(CLTTWO, ADDRTYPE, BIRTHP, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTDODX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSEX, CLTSTAT, CTRYCODE, DIRMAIL, DOCNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, MARRYD, NATLTY, NMFMT, OCCPCODE, SALUTL, SECUITYNO, SERVBRH, SOE, SRDATE, STATCODE, TAXFLAG, VIP, ZDOCTIND, FAXNO, OLDIDNO, RDIDTELNO, RINTERNET, RMBLPHONE, RPAGER, RSTAFLAG, RTAXIDNUM, ZSPECIND, DECGRSAL, EMPRTAXR, EVIDDATE, INCDESC, PAYROLLNO, PENSIND, PRASIND, SALCURR, TAXYR, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterPersonalClient> CLIUPPAsync(
                    string CLTTWO, 
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLIUPPAsync(CLTTWO, ADDRTYPE, BIRTHP, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTDODX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSEX, CLTSTAT, CTRYCODE, DIRMAIL, DOCNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, MARRYD, NATLTY, NMFMT, OCCPCODE, SALUTL, SECUITYNO, SERVBRH, SOE, SRDATE, STATCODE, TAXFLAG, VIP, ZDOCTIND, FAXNO, OLDIDNO, RDIDTELNO, RINTERNET, RMBLPHONE, RPAGER, RSTAFLAG, RTAXIDNUM, ZSPECIND, DECGRSAL, EMPRTAXR, EVIDDATE, INCDESC, PAYROLLNO, PENSIND, PRASIND, SALCURR, TAXYR, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LABankEnquiry.MasterClientBankAccCreate CBACRT(string CBANKSEL, string BANKACCDSC, string BANKACOUNT, string BANKKEY, string BNKACTYP, string CURRCODE, string DATEFROM, string FACTHOUS, string SCTYCDE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CBACRT(CBANKSEL, BANKACCDSC, BANKACOUNT, BANKKEY, BNKACTYP, CURRCODE, DATEFROM, FACTHOUS, SCTYCDE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccCreate> CBACRTAsync(string CBANKSEL, string BANKACCDSC, string BANKACOUNT, string BANKKEY, string BNKACTYP, string CURRCODE, string DATEFROM, string FACTHOUS, string SCTYCDE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CBACRTAsync(CBANKSEL, BANKACCDSC, BANKACOUNT, BANKKEY, BNKACTYP, CURRCODE, DATEFROM, FACTHOUS, SCTYCDE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LABankEnquiry.MasterClientBankAccEnquiry CBAENQ(string CBANKSEL, string BANKACOUNT, string BANKKEY, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CBAENQ(CBANKSEL, BANKACOUNT, BANKKEY, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccEnquiry> CBAENQAsync(string CBANKSEL, string BANKACOUNT, string BANKKEY, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CBAENQAsync(CBANKSEL, BANKACOUNT, BANKKEY, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LABankEnquiry.MasterClientBankAccUpdate CBAUPD(
                    string CBANKSEL, 
                    string BANKACCDSC, 
                    string BANKACOUNT, 
                    string BANKKEY, 
                    string BNKACTYP, 
                    string CURRCODE, 
                    string DATEFROM, 
                    string DATTO, 
                    string FACTHOUS, 
                    string SCTYCDE, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CBAUPD(CBANKSEL, BANKACCDSC, BANKACOUNT, BANKKEY, BNKACTYP, CURRCODE, DATEFROM, DATTO, FACTHOUS, SCTYCDE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABankEnquiry.MasterClientBankAccUpdate> CBAUPDAsync(
                    string CBANKSEL, 
                    string BANKACCDSC, 
                    string BANKACOUNT, 
                    string BANKKEY, 
                    string BNKACTYP, 
                    string CURRCODE, 
                    string DATEFROM, 
                    string DATTO, 
                    string FACTHOUS, 
                    string SCTYCDE, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CBAUPDAsync(CBANKSEL, BANKACCDSC, BANKACOUNT, BANKKEY, BNKACTYP, CURRCODE, DATEFROM, DATTO, FACTHOUS, SCTYCDE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
