//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAClientCreationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterCreate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLNTNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLNTNUM {
            get {
                return this.CLNTNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.CLNTNUMField, value) != true)) {
                    this.CLNTNUMField = value;
                    this.RaisePropertyChanged("CLNTNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAClientCreationService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLICRC", ReplyAction="http://tempuri.org/IService/CLICRCResponse")]
        UWSaralServices.LAClientCreationService.MasterCreate CLICRC(
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string CATEGORY, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLICRC", ReplyAction="http://tempuri.org/IService/CLICRCResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAClientCreationService.MasterCreate> CLICRCAsync(
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string CATEGORY, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLICRP", ReplyAction="http://tempuri.org/IService/CLICRPResponse")]
        UWSaralServices.LAClientCreationService.MasterCreate CLICRP(
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CLICRP", ReplyAction="http://tempuri.org/IService/CLICRPResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAClientCreationService.MasterCreate> CLICRPAsync(
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LAClientCreationService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LAClientCreationService.IService>, UWSaralServices.LAClientCreationService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LAClientCreationService.MasterCreate CLICRC(
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string CATEGORY, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLICRC(CAPITAL, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSTAT, CTRYCODE, CTRYORIG, DIRMAIL, ECACT, FAO, FAXNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, SECUITYNO, SERVBRH, SRDATE, STAFFNO, CATEGORY, TAXFLAG, TGRAM, TLXNO, VIP, OLDIDNO, RINTERNET, RTAXIDNUM, ZSPECIND, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAClientCreationService.MasterCreate> CLICRCAsync(
                    string CAPITAL, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string CTRYORIG, 
                    string DIRMAIL, 
                    string ECACT, 
                    string FAO, 
                    string FAXNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SRDATE, 
                    string STAFFNO, 
                    string CATEGORY, 
                    string TAXFLAG, 
                    string TGRAM, 
                    string TLXNO, 
                    string VIP, 
                    string OLDIDNO, 
                    string RINTERNET, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLICRCAsync(CAPITAL, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSTAT, CTRYCODE, CTRYORIG, DIRMAIL, ECACT, FAO, FAXNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, SECUITYNO, SERVBRH, SRDATE, STAFFNO, CATEGORY, TAXFLAG, TGRAM, TLXNO, VIP, OLDIDNO, RINTERNET, RTAXIDNUM, ZSPECIND, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAClientCreationService.MasterCreate CLICRP(
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLICRP(ADDRTYPE, BIRTHP, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTDODX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSEX, CLTSTAT, CTRYCODE, DIRMAIL, DOCNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, MARRYD, NATLTY, NMFMT, OCCPCODE, SALUTL, SECUITYNO, SERVBRH, SOE, SRDATE, STATCODE, TAXFLAG, VIP, ZDOCTIND, FAXNO, OLDIDNO, RDIDTELNO, RINTERNET, RMBLPHONE, RPAGER, RSTAFLAG, RTAXIDNUM, ZSPECIND, DECGRSAL, EMPRTAXR, EVIDDATE, INCDESC, PAYROLLNO, PENSIND, PRASIND, SALCURR, TAXYR, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAClientCreationService.MasterCreate> CLICRPAsync(
                    string ADDRTYPE, 
                    string BIRTHP, 
                    string CLTADDR01, 
                    string CLTADDR02, 
                    string CLTADDR03, 
                    string CLTADDR04, 
                    string CLTADDR05, 
                    string CLTDOBX, 
                    string CLTDODX, 
                    string CLTPCODE, 
                    string CLTPHONE01, 
                    string CLTPHONE02, 
                    string CLTSEX, 
                    string CLTSTAT, 
                    string CTRYCODE, 
                    string DIRMAIL, 
                    string DOCNO, 
                    string LANGUAGE, 
                    string LGIVNAME, 
                    string LSURNAME, 
                    string MAILING, 
                    string MARRYD, 
                    string NATLTY, 
                    string NMFMT, 
                    string OCCPCODE, 
                    string SALUTL, 
                    string SECUITYNO, 
                    string SERVBRH, 
                    string SOE, 
                    string SRDATE, 
                    string STATCODE, 
                    string TAXFLAG, 
                    string VIP, 
                    string ZDOCTIND, 
                    string FAXNO, 
                    string OLDIDNO, 
                    string RDIDTELNO, 
                    string RINTERNET, 
                    string RMBLPHONE, 
                    string RPAGER, 
                    string RSTAFLAG, 
                    string RTAXIDNUM, 
                    string ZSPECIND, 
                    string DECGRSAL, 
                    string EMPRTAXR, 
                    string EVIDDATE, 
                    string INCDESC, 
                    string PAYROLLNO, 
                    string PENSIND, 
                    string PRASIND, 
                    string SALCURR, 
                    string TAXYR, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.CLICRPAsync(ADDRTYPE, BIRTHP, CLTADDR01, CLTADDR02, CLTADDR03, CLTADDR04, CLTADDR05, CLTDOBX, CLTDODX, CLTPCODE, CLTPHONE01, CLTPHONE02, CLTSEX, CLTSTAT, CTRYCODE, DIRMAIL, DOCNO, LANGUAGE, LGIVNAME, LSURNAME, MAILING, MARRYD, NATLTY, NMFMT, OCCPCODE, SALUTL, SECUITYNO, SERVBRH, SOE, SRDATE, STATCODE, TAXFLAG, VIP, ZDOCTIND, FAXNO, OLDIDNO, RDIDTELNO, RINTERNET, RMBLPHONE, RPAGER, RSTAFLAG, RTAXIDNUM, ZSPECIND, DECGRSAL, EMPRTAXR, EVIDDATE, INCDESC, PAYROLLNO, PENSIND, PRASIND, SALCURR, TAXYR, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
