//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAPreIssueValService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPolicyPreIssue", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterPolicyPreIssue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNTFEEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRTABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDUCAMT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERORDSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INSTPRMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PREMSUSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRMDEPSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STAXAMT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZBCKDINT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZTAMTDUEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNTFEE {
            get {
                return this.CNTFEEField;
            }
            set {
                if ((object.ReferenceEquals(this.CNTFEEField, value) != true)) {
                    this.CNTFEEField = value;
                    this.RaisePropertyChanged("CNTFEE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRTABLE {
            get {
                return this.CRTABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRTABLEField, value) != true)) {
                    this.CRTABLEField = value;
                    this.RaisePropertyChanged("CRTABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDUCAMT01 {
            get {
                return this.EDUCAMT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.EDUCAMT01Field, value) != true)) {
                    this.EDUCAMT01Field = value;
                    this.RaisePropertyChanged("EDUCAMT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERORDSC {
            get {
                return this.ERORDSCField;
            }
            set {
                if ((object.ReferenceEquals(this.ERORDSCField, value) != true)) {
                    this.ERORDSCField = value;
                    this.RaisePropertyChanged("ERORDSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INSTPRM {
            get {
                return this.INSTPRMField;
            }
            set {
                if ((object.ReferenceEquals(this.INSTPRMField, value) != true)) {
                    this.INSTPRMField = value;
                    this.RaisePropertyChanged("INSTPRM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PREMSUSP {
            get {
                return this.PREMSUSPField;
            }
            set {
                if ((object.ReferenceEquals(this.PREMSUSPField, value) != true)) {
                    this.PREMSUSPField = value;
                    this.RaisePropertyChanged("PREMSUSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRMDEPST {
            get {
                return this.PRMDEPSTField;
            }
            set {
                if ((object.ReferenceEquals(this.PRMDEPSTField, value) != true)) {
                    this.PRMDEPSTField = value;
                    this.RaisePropertyChanged("PRMDEPST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STAXAMT01 {
            get {
                return this.STAXAMT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.STAXAMT01Field, value) != true)) {
                    this.STAXAMT01Field = value;
                    this.RaisePropertyChanged("STAXAMT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZBCKDINT01 {
            get {
                return this.ZBCKDINT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZBCKDINT01Field, value) != true)) {
                    this.ZBCKDINT01Field = value;
                    this.RaisePropertyChanged("ZBCKDINT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZTAMTDUE {
            get {
                return this.ZTAMTDUEField;
            }
            set {
                if ((object.ReferenceEquals(this.ZTAMTDUEField, value) != true)) {
                    this.ZTAMTDUEField = value;
                    this.RaisePropertyChanged("ZTAMTDUE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPolicyIssuance", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterPolicyIssuance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BILLFREQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNTFEEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRTABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDUCAMT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERORDSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INSTPRMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OCCDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PREMSUSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRMDEPSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STAXAMT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZBCKDINT01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZTAMTDUEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENTNAME {
            get {
                return this.AGENTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENTNAMEField, value) != true)) {
                    this.AGENTNAMEField = value;
                    this.RaisePropertyChanged("AGENTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BILLFREQ {
            get {
                return this.BILLFREQField;
            }
            set {
                if ((object.ReferenceEquals(this.BILLFREQField, value) != true)) {
                    this.BILLFREQField = value;
                    this.RaisePropertyChanged("BILLFREQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNTFEE {
            get {
                return this.CNTFEEField;
            }
            set {
                if ((object.ReferenceEquals(this.CNTFEEField, value) != true)) {
                    this.CNTFEEField = value;
                    this.RaisePropertyChanged("CNTFEE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRTABLE {
            get {
                return this.CRTABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRTABLEField, value) != true)) {
                    this.CRTABLEField = value;
                    this.RaisePropertyChanged("CRTABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDUCAMT01 {
            get {
                return this.EDUCAMT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.EDUCAMT01Field, value) != true)) {
                    this.EDUCAMT01Field = value;
                    this.RaisePropertyChanged("EDUCAMT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERORDSC {
            get {
                return this.ERORDSCField;
            }
            set {
                if ((object.ReferenceEquals(this.ERORDSCField, value) != true)) {
                    this.ERORDSCField = value;
                    this.RaisePropertyChanged("ERORDSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INSTPRM {
            get {
                return this.INSTPRMField;
            }
            set {
                if ((object.ReferenceEquals(this.INSTPRMField, value) != true)) {
                    this.INSTPRMField = value;
                    this.RaisePropertyChanged("INSTPRM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OCCDATE {
            get {
                return this.OCCDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.OCCDATEField, value) != true)) {
                    this.OCCDATEField = value;
                    this.RaisePropertyChanged("OCCDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PREMSUSP {
            get {
                return this.PREMSUSPField;
            }
            set {
                if ((object.ReferenceEquals(this.PREMSUSPField, value) != true)) {
                    this.PREMSUSPField = value;
                    this.RaisePropertyChanged("PREMSUSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRMDEPST {
            get {
                return this.PRMDEPSTField;
            }
            set {
                if ((object.ReferenceEquals(this.PRMDEPSTField, value) != true)) {
                    this.PRMDEPSTField = value;
                    this.RaisePropertyChanged("PRMDEPST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STAXAMT01 {
            get {
                return this.STAXAMT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.STAXAMT01Field, value) != true)) {
                    this.STAXAMT01Field = value;
                    this.RaisePropertyChanged("STAXAMT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZBCKDINT01 {
            get {
                return this.ZBCKDINT01Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZBCKDINT01Field, value) != true)) {
                    this.ZBCKDINT01Field = value;
                    this.RaisePropertyChanged("ZBCKDINT01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZTAMTDUE {
            get {
                return this.ZTAMTDUEField;
            }
            set {
                if ((object.ReferenceEquals(this.ZTAMTDUEField, value) != true)) {
                    this.ZTAMTDUEField = value;
                    this.RaisePropertyChanged("ZTAMTDUE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAPreIssueValService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PRPPREISS", ReplyAction="http://tempuri.org/IService/PRPPREISSResponse")]
        UWSaralServices.LAPreIssueValService.MasterPolicyPreIssue[] PRPPREISS(string CHDRSEL, string DATIME, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PRPPREISS", ReplyAction="http://tempuri.org/IService/PRPPREISSResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAPreIssueValService.MasterPolicyPreIssue[]> PRPPREISSAsync(string CHDRSEL, string DATIME, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/NBPISSUE", ReplyAction="http://tempuri.org/IService/NBPISSUEResponse")]
        UWSaralServices.LAPreIssueValService.MasterPolicyIssuance[] NBPISSUE(
                    string CHDRSEL, 
                    string DATIME, 
                    string AGNUM, 
                    string REPORTAG01, 
                    string REPORTAG02, 
                    string ZZSRCE01, 
                    string ZZSRCE02, 
                    string ZARACDE, 
                    string ZFEREGN01, 
                    string ZFEREGN02, 
                    string ZFEZONE01, 
                    string ZFEZONE02, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/NBPISSUE", ReplyAction="http://tempuri.org/IService/NBPISSUEResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAPreIssueValService.MasterPolicyIssuance[]> NBPISSUEAsync(
                    string CHDRSEL, 
                    string DATIME, 
                    string AGNUM, 
                    string REPORTAG01, 
                    string REPORTAG02, 
                    string ZZSRCE01, 
                    string ZZSRCE02, 
                    string ZARACDE, 
                    string ZFEREGN01, 
                    string ZFEREGN02, 
                    string ZFEZONE01, 
                    string ZFEZONE02, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LAPreIssueValService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LAPreIssueValService.IService>, UWSaralServices.LAPreIssueValService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LAPreIssueValService.MasterPolicyPreIssue[] PRPPREISS(string CHDRSEL, string DATIME, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.PRPPREISS(CHDRSEL, DATIME, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAPreIssueValService.MasterPolicyPreIssue[]> PRPPREISSAsync(string CHDRSEL, string DATIME, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.PRPPREISSAsync(CHDRSEL, DATIME, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAPreIssueValService.MasterPolicyIssuance[] NBPISSUE(
                    string CHDRSEL, 
                    string DATIME, 
                    string AGNUM, 
                    string REPORTAG01, 
                    string REPORTAG02, 
                    string ZZSRCE01, 
                    string ZZSRCE02, 
                    string ZARACDE, 
                    string ZFEREGN01, 
                    string ZFEREGN02, 
                    string ZFEZONE01, 
                    string ZFEZONE02, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.NBPISSUE(CHDRSEL, DATIME, AGNUM, REPORTAG01, REPORTAG02, ZZSRCE01, ZZSRCE02, ZARACDE, ZFEREGN01, ZFEREGN02, ZFEZONE01, ZFEZONE02, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAPreIssueValService.MasterPolicyIssuance[]> NBPISSUEAsync(
                    string CHDRSEL, 
                    string DATIME, 
                    string AGNUM, 
                    string REPORTAG01, 
                    string REPORTAG02, 
                    string ZZSRCE01, 
                    string ZZSRCE02, 
                    string ZARACDE, 
                    string ZFEREGN01, 
                    string ZFEREGN02, 
                    string ZFEZONE01, 
                    string ZFEZONE02, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.NBPISSUEAsync(CHDRSEL, DATIME, AGNUM, REPORTAG01, REPORTAG02, ZZSRCE01, ZZSRCE02, ZARACDE, ZFEREGN01, ZFEREGN02, ZFEZONE01, ZFEZONE02, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
