//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAFSARCalculationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterUnderwriting", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterUnderwriting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHDRNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNTTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRTABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SICURRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TSUMINSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHDRNUM {
            get {
                return this.CHDRNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.CHDRNUMField, value) != true)) {
                    this.CHDRNUMField = value;
                    this.RaisePropertyChanged("CHDRNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNTTYPE {
            get {
                return this.CNTTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.CNTTYPEField, value) != true)) {
                    this.CNTTYPEField = value;
                    this.RaisePropertyChanged("CNTTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANY {
            get {
                return this.COMPANYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYField, value) != true)) {
                    this.COMPANYField = value;
                    this.RaisePropertyChanged("COMPANY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRTABLE {
            get {
                return this.CRTABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRTABLEField, value) != true)) {
                    this.CRTABLEField = value;
                    this.RaisePropertyChanged("CRTABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SICURR {
            get {
                return this.SICURRField;
            }
            set {
                if ((object.ReferenceEquals(this.SICURRField, value) != true)) {
                    this.SICURRField = value;
                    this.RaisePropertyChanged("SICURR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUMIN {
            get {
                return this.SUMINField;
            }
            set {
                if ((object.ReferenceEquals(this.SUMINField, value) != true)) {
                    this.SUMINField = value;
                    this.RaisePropertyChanged("SUMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TSUMINS {
            get {
                return this.TSUMINSField;
            }
            set {
                if ((object.ReferenceEquals(this.TSUMINSField, value) != true)) {
                    this.TSUMINSField = value;
                    this.RaisePropertyChanged("TSUMINS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAFSARCalculationService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWECON", ReplyAction="http://tempuri.org/IService/UWECONResponse")]
        UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWECON(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWECON", ReplyAction="http://tempuri.org/IService/UWECONResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWECONAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWEFSA", ReplyAction="http://tempuri.org/IService/UWEFSAResponse")]
        UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWEFSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWEFSA", ReplyAction="http://tempuri.org/IService/UWEFSAResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWEFSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWERSA", ReplyAction="http://tempuri.org/IService/UWERSAResponse")]
        UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWERSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWERSA", ReplyAction="http://tempuri.org/IService/UWERSAResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWERSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWESSA", ReplyAction="http://tempuri.org/IService/UWESSAResponse")]
        UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWESSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWESSA", ReplyAction="http://tempuri.org/IService/UWESSAResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWESSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWETSA", ReplyAction="http://tempuri.org/IService/UWETSAResponse")]
        UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWETSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UWETSA", ReplyAction="http://tempuri.org/IService/UWETSAResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWETSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LAFSARCalculationService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LAFSARCalculationService.IService>, UWSaralServices.LAFSARCalculationService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWECON(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWECON(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWECONAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWECONAsync(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWEFSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWEFSA(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWEFSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWEFSAAsync(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWERSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWERSA(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWERSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWERSAAsync(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWESSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWESSA(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWESSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWESSAAsync(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LAFSARCalculationService.MasterUnderwriting[] UWETSA(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWETSA(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAFSARCalculationService.MasterUnderwriting[]> UWETSAAsync(string CLNTNUM, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.UWETSAAsync(CLNTNUM, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
