//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPAMEDICALINTEGRATIONSYNC.TPARegisteration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TPARegisteration.IHITPA_PIMS")]
    public interface IHITPA_PIMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterNewCase", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterNewCaseResponse")]
        UWSaralServices.TPARegisteration.ResponseMessage RegisterNewCase(string UserName, string Password, UWSaralServices.TPARegisteration.ProposalDetails proposalDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterNewCase", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterNewCaseResponse")]
        System.Threading.Tasks.Task<UWSaralServices.TPARegisteration.ResponseMessage> RegisterNewCaseAsync(string UserName, string Password, UWSaralServices.TPARegisteration.ProposalDetails proposalDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterCase", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterCaseResponse")]
        string RegisterCase(
                    string UserName, 
                    string Password, 
                    string ProposalDate, 
                    string ProposalNo, 
                    string MasterPolicyNo, 
                    string ProposerInitial, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string Telephone, 
                    string MobileNo, 
                    string HNIFlag, 
                    string HomeVisitFlag, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string Channel, 
                    string BranchName, 
                    string PlanType, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string Remark, 
                    string PreferredDate, 
                    string PreferredTime, 
                    string PreferredProviderNo, 
                    string Age, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailId, 
                    string PaymentType, 
                    string Status, 
                    string ApplicantOfficeNumber, 
                    string DCName, 
                    string ProposalStatus, 
                    string CashieringDate, 
                    string CashieredAmount, 
                    string PCName, 
                    string Region, 
                    string RepeatCase, 
                    string TPACost, 
                    string PreferredDCDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterCase", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterCaseResponse")]
        System.Threading.Tasks.Task<string> RegisterCaseAsync(
                    string UserName, 
                    string Password, 
                    string ProposalDate, 
                    string ProposalNo, 
                    string MasterPolicyNo, 
                    string ProposerInitial, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string Telephone, 
                    string MobileNo, 
                    string HNIFlag, 
                    string HomeVisitFlag, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string Channel, 
                    string BranchName, 
                    string PlanType, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string Remark, 
                    string PreferredDate, 
                    string PreferredTime, 
                    string PreferredProviderNo, 
                    string Age, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailId, 
                    string PaymentType, 
                    string Status, 
                    string ApplicantOfficeNumber, 
                    string DCName, 
                    string ProposalStatus, 
                    string CashieringDate, 
                    string CashieredAmount, 
                    string PCName, 
                    string Region, 
                    string RepeatCase, 
                    string TPACost, 
                    string PreferredDCDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterCase_TATA_AIA", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterCase_TATA_AIAResponse")]
        string RegisterCase_TATA_AIA(
                    string UserName, 
                    string Password, 
                    string Channel, 
                    string BranchName, 
                    string ClientName, 
                    string ApplicationNo, 
                    string Gender, 
                    string PhoneNo, 
                    string MobileNo, 
                    string HNIFlag, 
                    string DOB, 
                    string ClientEmail, 
                    string Address, 
                    string City, 
                    string State, 
                    string PinCode, 
                    string TestDetails, 
                    string ProviderNumber, 
                    string ProviderName, 
                    string FirstAppointmentDate, 
                    string FirstAppointmentTime, 
                    string SecondAppointmentDate, 
                    string SecondAppointmentTime, 
                    string VisitType, 
                    string RMName, 
                    string RMContact, 
                    string SHNI_, 
                    string Priority_, 
                    string Premium_, 
                    string SumInsured_, 
                    string ProviderCode_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/RegisterCase_TATA_AIA", ReplyAction="http://tempuri.org/IHITPA_PIMS/RegisterCase_TATA_AIAResponse")]
        System.Threading.Tasks.Task<string> RegisterCase_TATA_AIAAsync(
                    string UserName, 
                    string Password, 
                    string Channel, 
                    string BranchName, 
                    string ClientName, 
                    string ApplicationNo, 
                    string Gender, 
                    string PhoneNo, 
                    string MobileNo, 
                    string HNIFlag, 
                    string DOB, 
                    string ClientEmail, 
                    string Address, 
                    string City, 
                    string State, 
                    string PinCode, 
                    string TestDetails, 
                    string ProviderNumber, 
                    string ProviderName, 
                    string FirstAppointmentDate, 
                    string FirstAppointmentTime, 
                    string SecondAppointmentDate, 
                    string SecondAppointmentTime, 
                    string VisitType, 
                    string RMName, 
                    string RMContact, 
                    string SHNI_, 
                    string Priority_, 
                    string Premium_, 
                    string SumInsured_, 
                    string ProviderCode_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/GetDCList", ReplyAction="http://tempuri.org/IHITPA_PIMS/GetDCListResponse")]
        string GetDCList(string UserName, string Password, string City, string State, string Area, string PinCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/GetDCList", ReplyAction="http://tempuri.org/IHITPA_PIMS/GetDCListResponse")]
        System.Threading.Tasks.Task<string> GetDCListAsync(string UserName, string Password, string City, string State, string Area, string PinCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/UpdatePreference", ReplyAction="http://tempuri.org/IHITPA_PIMS/UpdatePreferenceResponse")]
        UWSaralServices.TPARegisteration.ResponseMessage UpdatePreference(string UserName, string Password, UWSaralServices.TPARegisteration.PreferenceDetails preferenceDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/UpdatePreference", ReplyAction="http://tempuri.org/IHITPA_PIMS/UpdatePreferenceResponse")]
        System.Threading.Tasks.Task<UWSaralServices.TPARegisteration.ResponseMessage> UpdatePreferenceAsync(string UserName, string Password, UWSaralServices.TPARegisteration.PreferenceDetails preferenceDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/StatusUpdateFromBajaj", ReplyAction="http://tempuri.org/IHITPA_PIMS/StatusUpdateFromBajajResponse")]
        string StatusUpdateFromBajaj(string UserName, string Password, string AppointmentCode, string MasterPolicyNo, string StatusFromBajaj, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/StatusUpdateFromBajaj", ReplyAction="http://tempuri.org/IHITPA_PIMS/StatusUpdateFromBajajResponse")]
        System.Threading.Tasks.Task<string> StatusUpdateFromBajajAsync(string UserName, string Password, string AppointmentCode, string MasterPolicyNo, string StatusFromBajaj, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/AppointmentBooking_BALIC", ReplyAction="http://tempuri.org/IHITPA_PIMS/AppointmentBooking_BALICResponse")]
        string AppointmentBooking_BALIC(
                    string UserName, 
                    string Password, 
                    string ProposalNo, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string MobileNo, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailID, 
                    string ApplicationNo, 
                    string PANNoofIP, 
                    string NomineeName, 
                    string NomineeDOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHITPA_PIMS/AppointmentBooking_BALIC", ReplyAction="http://tempuri.org/IHITPA_PIMS/AppointmentBooking_BALICResponse")]
        System.Threading.Tasks.Task<string> AppointmentBooking_BALICAsync(
                    string UserName, 
                    string Password, 
                    string ProposalNo, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string MobileNo, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailID, 
                    string ApplicationNo, 
                    string PANNoofIP, 
                    string NomineeName, 
                    string NomineeDOB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHITPA_PIMSChannel : TPAMEDICALINTEGRATIONSYNC.TPARegisteration.IHITPA_PIMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HITPA_PIMSClient : System.ServiceModel.ClientBase<TPAMEDICALINTEGRATIONSYNC.TPARegisteration.IHITPA_PIMS>, TPAMEDICALINTEGRATIONSYNC.TPARegisteration.IHITPA_PIMS {
        
        public HITPA_PIMSClient() {
        }
        
        public HITPA_PIMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HITPA_PIMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HITPA_PIMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HITPA_PIMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.TPARegisteration.ResponseMessage RegisterNewCase(string UserName, string Password, UWSaralServices.TPARegisteration.ProposalDetails proposalDetails) {
            return base.Channel.RegisterNewCase(UserName, Password, proposalDetails);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.TPARegisteration.ResponseMessage> RegisterNewCaseAsync(string UserName, string Password, UWSaralServices.TPARegisteration.ProposalDetails proposalDetails) {
            return base.Channel.RegisterNewCaseAsync(UserName, Password, proposalDetails);
        }
        
        public string RegisterCase(
                    string UserName, 
                    string Password, 
                    string ProposalDate, 
                    string ProposalNo, 
                    string MasterPolicyNo, 
                    string ProposerInitial, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string Telephone, 
                    string MobileNo, 
                    string HNIFlag, 
                    string HomeVisitFlag, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string Channel, 
                    string BranchName, 
                    string PlanType, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string Remark, 
                    string PreferredDate, 
                    string PreferredTime, 
                    string PreferredProviderNo, 
                    string Age, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailId, 
                    string PaymentType, 
                    string Status, 
                    string ApplicantOfficeNumber, 
                    string DCName, 
                    string ProposalStatus, 
                    string CashieringDate, 
                    string CashieredAmount, 
                    string PCName, 
                    string Region, 
                    string RepeatCase, 
                    string TPACost, 
                    string PreferredDCDetails) {
            return base.Channel.RegisterCase(UserName, Password, ProposalDate, ProposalNo, MasterPolicyNo, ProposerInitial, ProposerName, Gender, TestConducted, Address1, Address2, City, State, District, Taluka, Pincode, LandMark, Telephone, MobileNo, HNIFlag, HomeVisitFlag, AgentCode, AgentName, AgentContactDetails, Channel, BranchName, PlanType, ProductName, MemberDOB, CustomerEmail, Remark, PreferredDate, PreferredTime, PreferredProviderNo, Age, RMContactNumber, RMEmailId, IMDEmailId, PaymentType, Status, ApplicantOfficeNumber, DCName, ProposalStatus, CashieringDate, CashieredAmount, PCName, Region, RepeatCase, TPACost, PreferredDCDetails);
        }
        
        public System.Threading.Tasks.Task<string> RegisterCaseAsync(
                    string UserName, 
                    string Password, 
                    string ProposalDate, 
                    string ProposalNo, 
                    string MasterPolicyNo, 
                    string ProposerInitial, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string Telephone, 
                    string MobileNo, 
                    string HNIFlag, 
                    string HomeVisitFlag, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string Channel, 
                    string BranchName, 
                    string PlanType, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string Remark, 
                    string PreferredDate, 
                    string PreferredTime, 
                    string PreferredProviderNo, 
                    string Age, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailId, 
                    string PaymentType, 
                    string Status, 
                    string ApplicantOfficeNumber, 
                    string DCName, 
                    string ProposalStatus, 
                    string CashieringDate, 
                    string CashieredAmount, 
                    string PCName, 
                    string Region, 
                    string RepeatCase, 
                    string TPACost, 
                    string PreferredDCDetails) {
            return base.Channel.RegisterCaseAsync(UserName, Password, ProposalDate, ProposalNo, MasterPolicyNo, ProposerInitial, ProposerName, Gender, TestConducted, Address1, Address2, City, State, District, Taluka, Pincode, LandMark, Telephone, MobileNo, HNIFlag, HomeVisitFlag, AgentCode, AgentName, AgentContactDetails, Channel, BranchName, PlanType, ProductName, MemberDOB, CustomerEmail, Remark, PreferredDate, PreferredTime, PreferredProviderNo, Age, RMContactNumber, RMEmailId, IMDEmailId, PaymentType, Status, ApplicantOfficeNumber, DCName, ProposalStatus, CashieringDate, CashieredAmount, PCName, Region, RepeatCase, TPACost, PreferredDCDetails);
        }
        
        public string RegisterCase_TATA_AIA(
                    string UserName, 
                    string Password, 
                    string Channel, 
                    string BranchName, 
                    string ClientName, 
                    string ApplicationNo, 
                    string Gender, 
                    string PhoneNo, 
                    string MobileNo, 
                    string HNIFlag, 
                    string DOB, 
                    string ClientEmail, 
                    string Address, 
                    string City, 
                    string State, 
                    string PinCode, 
                    string TestDetails, 
                    string ProviderNumber, 
                    string ProviderName, 
                    string FirstAppointmentDate, 
                    string FirstAppointmentTime, 
                    string SecondAppointmentDate, 
                    string SecondAppointmentTime, 
                    string VisitType, 
                    string RMName, 
                    string RMContact, 
                    string SHNI_, 
                    string Priority_, 
                    string Premium_, 
                    string SumInsured_, 
                    string ProviderCode_) {
            return base.Channel.RegisterCase_TATA_AIA(UserName, Password, Channel, BranchName, ClientName, ApplicationNo, Gender, PhoneNo, MobileNo, HNIFlag, DOB, ClientEmail, Address, City, State, PinCode, TestDetails, ProviderNumber, ProviderName, FirstAppointmentDate, FirstAppointmentTime, SecondAppointmentDate, SecondAppointmentTime, VisitType, RMName, RMContact, SHNI_, Priority_, Premium_, SumInsured_, ProviderCode_);
        }
        
        public System.Threading.Tasks.Task<string> RegisterCase_TATA_AIAAsync(
                    string UserName, 
                    string Password, 
                    string Channel, 
                    string BranchName, 
                    string ClientName, 
                    string ApplicationNo, 
                    string Gender, 
                    string PhoneNo, 
                    string MobileNo, 
                    string HNIFlag, 
                    string DOB, 
                    string ClientEmail, 
                    string Address, 
                    string City, 
                    string State, 
                    string PinCode, 
                    string TestDetails, 
                    string ProviderNumber, 
                    string ProviderName, 
                    string FirstAppointmentDate, 
                    string FirstAppointmentTime, 
                    string SecondAppointmentDate, 
                    string SecondAppointmentTime, 
                    string VisitType, 
                    string RMName, 
                    string RMContact, 
                    string SHNI_, 
                    string Priority_, 
                    string Premium_, 
                    string SumInsured_, 
                    string ProviderCode_) {
            return base.Channel.RegisterCase_TATA_AIAAsync(UserName, Password, Channel, BranchName, ClientName, ApplicationNo, Gender, PhoneNo, MobileNo, HNIFlag, DOB, ClientEmail, Address, City, State, PinCode, TestDetails, ProviderNumber, ProviderName, FirstAppointmentDate, FirstAppointmentTime, SecondAppointmentDate, SecondAppointmentTime, VisitType, RMName, RMContact, SHNI_, Priority_, Premium_, SumInsured_, ProviderCode_);
        }
        
        public string GetDCList(string UserName, string Password, string City, string State, string Area, string PinCode) {
            return base.Channel.GetDCList(UserName, Password, City, State, Area, PinCode);
        }
        
        public System.Threading.Tasks.Task<string> GetDCListAsync(string UserName, string Password, string City, string State, string Area, string PinCode) {
            return base.Channel.GetDCListAsync(UserName, Password, City, State, Area, PinCode);
        }
        
        public UWSaralServices.TPARegisteration.ResponseMessage UpdatePreference(string UserName, string Password, UWSaralServices.TPARegisteration.PreferenceDetails preferenceDetails) {
            return base.Channel.UpdatePreference(UserName, Password, preferenceDetails);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.TPARegisteration.ResponseMessage> UpdatePreferenceAsync(string UserName, string Password, UWSaralServices.TPARegisteration.PreferenceDetails preferenceDetails) {
            return base.Channel.UpdatePreferenceAsync(UserName, Password, preferenceDetails);
        }
        
        public string StatusUpdateFromBajaj(string UserName, string Password, string AppointmentCode, string MasterPolicyNo, string StatusFromBajaj, string Remarks) {
            return base.Channel.StatusUpdateFromBajaj(UserName, Password, AppointmentCode, MasterPolicyNo, StatusFromBajaj, Remarks);
        }
        
        public System.Threading.Tasks.Task<string> StatusUpdateFromBajajAsync(string UserName, string Password, string AppointmentCode, string MasterPolicyNo, string StatusFromBajaj, string Remarks) {
            return base.Channel.StatusUpdateFromBajajAsync(UserName, Password, AppointmentCode, MasterPolicyNo, StatusFromBajaj, Remarks);
        }
        
        public string AppointmentBooking_BALIC(
                    string UserName, 
                    string Password, 
                    string ProposalNo, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string MobileNo, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailID, 
                    string ApplicationNo, 
                    string PANNoofIP, 
                    string NomineeName, 
                    string NomineeDOB) {
            return base.Channel.AppointmentBooking_BALIC(UserName, Password, ProposalNo, ProposerName, Gender, TestConducted, Address1, Address2, City, State, District, Taluka, Pincode, LandMark, MobileNo, AgentCode, AgentName, AgentContactDetails, ProductName, MemberDOB, CustomerEmail, RMContactNumber, RMEmailId, IMDEmailID, ApplicationNo, PANNoofIP, NomineeName, NomineeDOB);
        }
        
        public System.Threading.Tasks.Task<string> AppointmentBooking_BALICAsync(
                    string UserName, 
                    string Password, 
                    string ProposalNo, 
                    string ProposerName, 
                    string Gender, 
                    string TestConducted, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string State, 
                    string District, 
                    string Taluka, 
                    string Pincode, 
                    string LandMark, 
                    string MobileNo, 
                    string AgentCode, 
                    string AgentName, 
                    string AgentContactDetails, 
                    string ProductName, 
                    string MemberDOB, 
                    string CustomerEmail, 
                    string RMContactNumber, 
                    string RMEmailId, 
                    string IMDEmailID, 
                    string ApplicationNo, 
                    string PANNoofIP, 
                    string NomineeName, 
                    string NomineeDOB) {
            return base.Channel.AppointmentBooking_BALICAsync(UserName, Password, ProposalNo, ProposerName, Gender, TestConducted, Address1, Address2, City, State, District, Taluka, Pincode, LandMark, MobileNo, AgentCode, AgentName, AgentContactDetails, ProductName, MemberDOB, CustomerEmail, RMContactNumber, RMEmailId, IMDEmailID, ApplicationNo, PANNoofIP, NomineeName, NomineeDOB);
        }
    }
}
