//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LALoadingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPersonelLoadingCreate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterPersonelLoadingCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHDRNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COVERAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INSTPREMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RIDERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZLINSTPREMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHDRNUM {
            get {
                return this.CHDRNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.CHDRNUMField, value) != true)) {
                    this.CHDRNUMField = value;
                    this.RaisePropertyChanged("CHDRNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COVERAGE {
            get {
                return this.COVERAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.COVERAGEField, value) != true)) {
                    this.COVERAGEField = value;
                    this.RaisePropertyChanged("COVERAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INSTPREM {
            get {
                return this.INSTPREMField;
            }
            set {
                if ((object.ReferenceEquals(this.INSTPREMField, value) != true)) {
                    this.INSTPREMField = value;
                    this.RaisePropertyChanged("INSTPREM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIFE {
            get {
                return this.LIFEField;
            }
            set {
                if ((object.ReferenceEquals(this.LIFEField, value) != true)) {
                    this.LIFEField = value;
                    this.RaisePropertyChanged("LIFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RIDER {
            get {
                return this.RIDERField;
            }
            set {
                if ((object.ReferenceEquals(this.RIDERField, value) != true)) {
                    this.RIDERField = value;
                    this.RaisePropertyChanged("RIDER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZLINSTPREM {
            get {
                return this.ZLINSTPREMField;
            }
            set {
                if ((object.ReferenceEquals(this.ZLINSTPREMField, value) != true)) {
                    this.ZLINSTPREMField = value;
                    this.RaisePropertyChanged("ZLINSTPREM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterPersonelLoadingEnquiry", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MasterPersonelLoadingEnquiry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGERATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHDRNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ECESTRMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INSPRMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPCDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REASINDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SELECTLINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZFMORPCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNADJPERCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGERATE {
            get {
                return this.AGERATEField;
            }
            set {
                if ((object.ReferenceEquals(this.AGERATEField, value) != true)) {
                    this.AGERATEField = value;
                    this.RaisePropertyChanged("AGERATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHDRNUM {
            get {
                return this.CHDRNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.CHDRNUMField, value) != true)) {
                    this.CHDRNUMField = value;
                    this.RaisePropertyChanged("CHDRNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECESTRM {
            get {
                return this.ECESTRMField;
            }
            set {
                if ((object.ReferenceEquals(this.ECESTRMField, value) != true)) {
                    this.ECESTRMField = value;
                    this.RaisePropertyChanged("ECESTRM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INSPRM {
            get {
                return this.INSPRMField;
            }
            set {
                if ((object.ReferenceEquals(this.INSPRMField, value) != true)) {
                    this.INSPRMField = value;
                    this.RaisePropertyChanged("INSPRM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPCDA {
            get {
                return this.OPCDAField;
            }
            set {
                if ((object.ReferenceEquals(this.OPCDAField, value) != true)) {
                    this.OPCDAField = value;
                    this.RaisePropertyChanged("OPCDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPPC {
            get {
                return this.OPPCField;
            }
            set {
                if ((object.ReferenceEquals(this.OPPCField, value) != true)) {
                    this.OPPCField = value;
                    this.RaisePropertyChanged("OPPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REASIND {
            get {
                return this.REASINDField;
            }
            set {
                if ((object.ReferenceEquals(this.REASINDField, value) != true)) {
                    this.REASINDField = value;
                    this.RaisePropertyChanged("REASIND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SELECTLINE {
            get {
                return this.SELECTLINEField;
            }
            set {
                if ((object.ReferenceEquals(this.SELECTLINEField, value) != true)) {
                    this.SELECTLINEField = value;
                    this.RaisePropertyChanged("SELECTLINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZFMORPCT {
            get {
                return this.ZFMORPCTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZFMORPCTField, value) != true)) {
                    this.ZFMORPCTField = value;
                    this.RaisePropertyChanged("ZFMORPCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZNADJPERC {
            get {
                return this.ZNADJPERCField;
            }
            set {
                if ((object.ReferenceEquals(this.ZNADJPERCField, value) != true)) {
                    this.ZNADJPERCField = value;
                    this.RaisePropertyChanged("ZNADJPERC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LALoadingService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LODCRT", ReplyAction="http://tempuri.org/IService/LODCRTResponse")]
        UWSaralServices.LALoadingService.MasterPersonelLoadingCreate LODCRT(
                    string CHDRSEL, 
                    string LIFE, 
                    string COVERAGE, 
                    string RIDER, 
                    string CRTABLE, 
                    string AGERATE1, 
                    string AGERATE2, 
                    string AGERATE3, 
                    string AGERATE4, 
                    string AGERATE5, 
                    string AGERATE6, 
                    string AGERATE7, 
                    string AGERATE8, 
                    string ECESTRM1, 
                    string ECESTRM2, 
                    string ECESTRM3, 
                    string ECESTRM4, 
                    string ECESTRM5, 
                    string ECESTRM6, 
                    string ECESTRM7, 
                    string ECESTRM8, 
                    string INSPRM1, 
                    string INSPRM2, 
                    string INSPRM3, 
                    string INSPRM4, 
                    string INSPRM5, 
                    string INSPRM6, 
                    string INSPRM7, 
                    string INSPRM8, 
                    string OPCDA1, 
                    string OPCDA2, 
                    string OPCDA3, 
                    string OPCDA4, 
                    string OPCDA5, 
                    string OPCDA6, 
                    string OPCDA7, 
                    string OPCDA8, 
                    string OPPC1, 
                    string OPPC2, 
                    string OPPC3, 
                    string OPPC4, 
                    string OPPC5, 
                    string OPPC6, 
                    string OPPC7, 
                    string OPPC8, 
                    string REASIND1, 
                    string REASIND2, 
                    string REASIND3, 
                    string REASIND4, 
                    string REASIND5, 
                    string REASIND6, 
                    string REASIND7, 
                    string REASIND8, 
                    string SELECT1, 
                    string SELECT2, 
                    string SELECT3, 
                    string SELECT4, 
                    string SELECT5, 
                    string SELECT6, 
                    string SELECT7, 
                    string SELECT8, 
                    string ZFMORPCT1, 
                    string ZFMORPCT2, 
                    string ZFMORPCT3, 
                    string ZFMORPCT4, 
                    string ZFMORPCT5, 
                    string ZFMORPCT6, 
                    string ZFMORPCT7, 
                    string ZFMORPCT8, 
                    string ZNADJPERC1, 
                    string ZNADJPERC2, 
                    string ZNADJPERC3, 
                    string ZNADJPERC4, 
                    string ZNADJPERC5, 
                    string ZNADJPERC6, 
                    string ZNADJPERC7, 
                    string ZNADJPERC8, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LODCRT", ReplyAction="http://tempuri.org/IService/LODCRTResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LALoadingService.MasterPersonelLoadingCreate> LODCRTAsync(
                    string CHDRSEL, 
                    string LIFE, 
                    string COVERAGE, 
                    string RIDER, 
                    string CRTABLE, 
                    string AGERATE1, 
                    string AGERATE2, 
                    string AGERATE3, 
                    string AGERATE4, 
                    string AGERATE5, 
                    string AGERATE6, 
                    string AGERATE7, 
                    string AGERATE8, 
                    string ECESTRM1, 
                    string ECESTRM2, 
                    string ECESTRM3, 
                    string ECESTRM4, 
                    string ECESTRM5, 
                    string ECESTRM6, 
                    string ECESTRM7, 
                    string ECESTRM8, 
                    string INSPRM1, 
                    string INSPRM2, 
                    string INSPRM3, 
                    string INSPRM4, 
                    string INSPRM5, 
                    string INSPRM6, 
                    string INSPRM7, 
                    string INSPRM8, 
                    string OPCDA1, 
                    string OPCDA2, 
                    string OPCDA3, 
                    string OPCDA4, 
                    string OPCDA5, 
                    string OPCDA6, 
                    string OPCDA7, 
                    string OPCDA8, 
                    string OPPC1, 
                    string OPPC2, 
                    string OPPC3, 
                    string OPPC4, 
                    string OPPC5, 
                    string OPPC6, 
                    string OPPC7, 
                    string OPPC8, 
                    string REASIND1, 
                    string REASIND2, 
                    string REASIND3, 
                    string REASIND4, 
                    string REASIND5, 
                    string REASIND6, 
                    string REASIND7, 
                    string REASIND8, 
                    string SELECT1, 
                    string SELECT2, 
                    string SELECT3, 
                    string SELECT4, 
                    string SELECT5, 
                    string SELECT6, 
                    string SELECT7, 
                    string SELECT8, 
                    string ZFMORPCT1, 
                    string ZFMORPCT2, 
                    string ZFMORPCT3, 
                    string ZFMORPCT4, 
                    string ZFMORPCT5, 
                    string ZFMORPCT6, 
                    string ZFMORPCT7, 
                    string ZFMORPCT8, 
                    string ZNADJPERC1, 
                    string ZNADJPERC2, 
                    string ZNADJPERC3, 
                    string ZNADJPERC4, 
                    string ZNADJPERC5, 
                    string ZNADJPERC6, 
                    string ZNADJPERC7, 
                    string ZNADJPERC8, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LODENQ", ReplyAction="http://tempuri.org/IService/LODENQResponse")]
        UWSaralServices.LALoadingService.MasterPersonelLoadingEnquiry[] LODENQ(string CHDRSEL, string LIFE, string COVERAGE, string RIDER, string CRTABLE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LODENQ", ReplyAction="http://tempuri.org/IService/LODENQResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LALoadingService.MasterPersonelLoadingEnquiry[]> LODENQAsync(string CHDRSEL, string LIFE, string COVERAGE, string RIDER, string CRTABLE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.LALoadingService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.LALoadingService.IService>, UWSaralServices.LALoadingService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LALoadingService.MasterPersonelLoadingCreate LODCRT(
                    string CHDRSEL, 
                    string LIFE, 
                    string COVERAGE, 
                    string RIDER, 
                    string CRTABLE, 
                    string AGERATE1, 
                    string AGERATE2, 
                    string AGERATE3, 
                    string AGERATE4, 
                    string AGERATE5, 
                    string AGERATE6, 
                    string AGERATE7, 
                    string AGERATE8, 
                    string ECESTRM1, 
                    string ECESTRM2, 
                    string ECESTRM3, 
                    string ECESTRM4, 
                    string ECESTRM5, 
                    string ECESTRM6, 
                    string ECESTRM7, 
                    string ECESTRM8, 
                    string INSPRM1, 
                    string INSPRM2, 
                    string INSPRM3, 
                    string INSPRM4, 
                    string INSPRM5, 
                    string INSPRM6, 
                    string INSPRM7, 
                    string INSPRM8, 
                    string OPCDA1, 
                    string OPCDA2, 
                    string OPCDA3, 
                    string OPCDA4, 
                    string OPCDA5, 
                    string OPCDA6, 
                    string OPCDA7, 
                    string OPCDA8, 
                    string OPPC1, 
                    string OPPC2, 
                    string OPPC3, 
                    string OPPC4, 
                    string OPPC5, 
                    string OPPC6, 
                    string OPPC7, 
                    string OPPC8, 
                    string REASIND1, 
                    string REASIND2, 
                    string REASIND3, 
                    string REASIND4, 
                    string REASIND5, 
                    string REASIND6, 
                    string REASIND7, 
                    string REASIND8, 
                    string SELECT1, 
                    string SELECT2, 
                    string SELECT3, 
                    string SELECT4, 
                    string SELECT5, 
                    string SELECT6, 
                    string SELECT7, 
                    string SELECT8, 
                    string ZFMORPCT1, 
                    string ZFMORPCT2, 
                    string ZFMORPCT3, 
                    string ZFMORPCT4, 
                    string ZFMORPCT5, 
                    string ZFMORPCT6, 
                    string ZFMORPCT7, 
                    string ZFMORPCT8, 
                    string ZNADJPERC1, 
                    string ZNADJPERC2, 
                    string ZNADJPERC3, 
                    string ZNADJPERC4, 
                    string ZNADJPERC5, 
                    string ZNADJPERC6, 
                    string ZNADJPERC7, 
                    string ZNADJPERC8, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.LODCRT(CHDRSEL, LIFE, COVERAGE, RIDER, CRTABLE, AGERATE1, AGERATE2, AGERATE3, AGERATE4, AGERATE5, AGERATE6, AGERATE7, AGERATE8, ECESTRM1, ECESTRM2, ECESTRM3, ECESTRM4, ECESTRM5, ECESTRM6, ECESTRM7, ECESTRM8, INSPRM1, INSPRM2, INSPRM3, INSPRM4, INSPRM5, INSPRM6, INSPRM7, INSPRM8, OPCDA1, OPCDA2, OPCDA3, OPCDA4, OPCDA5, OPCDA6, OPCDA7, OPCDA8, OPPC1, OPPC2, OPPC3, OPPC4, OPPC5, OPPC6, OPPC7, OPPC8, REASIND1, REASIND2, REASIND3, REASIND4, REASIND5, REASIND6, REASIND7, REASIND8, SELECT1, SELECT2, SELECT3, SELECT4, SELECT5, SELECT6, SELECT7, SELECT8, ZFMORPCT1, ZFMORPCT2, ZFMORPCT3, ZFMORPCT4, ZFMORPCT5, ZFMORPCT6, ZFMORPCT7, ZFMORPCT8, ZNADJPERC1, ZNADJPERC2, ZNADJPERC3, ZNADJPERC4, ZNADJPERC5, ZNADJPERC6, ZNADJPERC7, ZNADJPERC8, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LALoadingService.MasterPersonelLoadingCreate> LODCRTAsync(
                    string CHDRSEL, 
                    string LIFE, 
                    string COVERAGE, 
                    string RIDER, 
                    string CRTABLE, 
                    string AGERATE1, 
                    string AGERATE2, 
                    string AGERATE3, 
                    string AGERATE4, 
                    string AGERATE5, 
                    string AGERATE6, 
                    string AGERATE7, 
                    string AGERATE8, 
                    string ECESTRM1, 
                    string ECESTRM2, 
                    string ECESTRM3, 
                    string ECESTRM4, 
                    string ECESTRM5, 
                    string ECESTRM6, 
                    string ECESTRM7, 
                    string ECESTRM8, 
                    string INSPRM1, 
                    string INSPRM2, 
                    string INSPRM3, 
                    string INSPRM4, 
                    string INSPRM5, 
                    string INSPRM6, 
                    string INSPRM7, 
                    string INSPRM8, 
                    string OPCDA1, 
                    string OPCDA2, 
                    string OPCDA3, 
                    string OPCDA4, 
                    string OPCDA5, 
                    string OPCDA6, 
                    string OPCDA7, 
                    string OPCDA8, 
                    string OPPC1, 
                    string OPPC2, 
                    string OPPC3, 
                    string OPPC4, 
                    string OPPC5, 
                    string OPPC6, 
                    string OPPC7, 
                    string OPPC8, 
                    string REASIND1, 
                    string REASIND2, 
                    string REASIND3, 
                    string REASIND4, 
                    string REASIND5, 
                    string REASIND6, 
                    string REASIND7, 
                    string REASIND8, 
                    string SELECT1, 
                    string SELECT2, 
                    string SELECT3, 
                    string SELECT4, 
                    string SELECT5, 
                    string SELECT6, 
                    string SELECT7, 
                    string SELECT8, 
                    string ZFMORPCT1, 
                    string ZFMORPCT2, 
                    string ZFMORPCT3, 
                    string ZFMORPCT4, 
                    string ZFMORPCT5, 
                    string ZFMORPCT6, 
                    string ZFMORPCT7, 
                    string ZFMORPCT8, 
                    string ZNADJPERC1, 
                    string ZNADJPERC2, 
                    string ZNADJPERC3, 
                    string ZNADJPERC4, 
                    string ZNADJPERC5, 
                    string ZNADJPERC6, 
                    string ZNADJPERC7, 
                    string ZNADJPERC8, 
                    string Branch, 
                    string UserRole, 
                    string UserID, 
                    string PartnerID, 
                    string ProcessID, 
                    string ApplicationNo) {
            return base.Channel.LODCRTAsync(CHDRSEL, LIFE, COVERAGE, RIDER, CRTABLE, AGERATE1, AGERATE2, AGERATE3, AGERATE4, AGERATE5, AGERATE6, AGERATE7, AGERATE8, ECESTRM1, ECESTRM2, ECESTRM3, ECESTRM4, ECESTRM5, ECESTRM6, ECESTRM7, ECESTRM8, INSPRM1, INSPRM2, INSPRM3, INSPRM4, INSPRM5, INSPRM6, INSPRM7, INSPRM8, OPCDA1, OPCDA2, OPCDA3, OPCDA4, OPCDA5, OPCDA6, OPCDA7, OPCDA8, OPPC1, OPPC2, OPPC3, OPPC4, OPPC5, OPPC6, OPPC7, OPPC8, REASIND1, REASIND2, REASIND3, REASIND4, REASIND5, REASIND6, REASIND7, REASIND8, SELECT1, SELECT2, SELECT3, SELECT4, SELECT5, SELECT6, SELECT7, SELECT8, ZFMORPCT1, ZFMORPCT2, ZFMORPCT3, ZFMORPCT4, ZFMORPCT5, ZFMORPCT6, ZFMORPCT7, ZFMORPCT8, ZNADJPERC1, ZNADJPERC2, ZNADJPERC3, ZNADJPERC4, ZNADJPERC5, ZNADJPERC6, ZNADJPERC7, ZNADJPERC8, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.LALoadingService.MasterPersonelLoadingEnquiry[] LODENQ(string CHDRSEL, string LIFE, string COVERAGE, string RIDER, string CRTABLE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.LODENQ(CHDRSEL, LIFE, COVERAGE, RIDER, CRTABLE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LALoadingService.MasterPersonelLoadingEnquiry[]> LODENQAsync(string CHDRSEL, string LIFE, string COVERAGE, string RIDER, string CRTABLE, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.LODENQAsync(CHDRSEL, LIFE, COVERAGE, RIDER, CRTABLE, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
