//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAAgentEnquiry {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.futuregenerali.in/life/LFAgentServiceBPMIntf", ConfigurationName="LAAgentEnquiry.LFAgentServiceBPMIntf")]
    public interface LFAgentServiceBPMIntf {
        
        // CODEGEN: Generating message contract since the operation getAgent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UWSaralServices.LAAgentEnquiry.getAgentResponse1 getAgent(UWSaralServices.LAAgentEnquiry.getAgentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UWSaralServices.LAAgentEnquiry.getAgentResponse1> getAgentAsync(UWSaralServices.LAAgentEnquiry.getAgentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.futuregenerali.in/life/LFAgentServiceBPMIntf")]
    public partial class getAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string agentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
                this.RaisePropertyChanged("agentCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://INBLRBPMLFDEV01:19086/schema/")]
    public partial class LF_ExceptionDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> errorFlagField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        public LF_ExceptionDetail() {
            this.errorFlagField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> errorFlag {
            get {
                return this.errorFlagField;
            }
            set {
                this.errorFlagField = value;
                this.RaisePropertyChanged("errorFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.futuregenerali.in/life")]
    public partial class LF_AgentDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentCode_AGNTSELField;
        
        private string agentNameField;
        
        private string channelDistributionField;
        
        private string agentStatusField;
        
        private string agentContactNumberField;
        
        private string designationCodeField;
        
        private string genderCodeField;
        
        private string agentUnitField;
        
        private string ulipStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string agentCode_AGNTSEL {
            get {
                return this.agentCode_AGNTSELField;
            }
            set {
                this.agentCode_AGNTSELField = value;
                this.RaisePropertyChanged("agentCode_AGNTSEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string agentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
                this.RaisePropertyChanged("agentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string channelDistribution {
            get {
                return this.channelDistributionField;
            }
            set {
                this.channelDistributionField = value;
                this.RaisePropertyChanged("channelDistribution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string agentStatus {
            get {
                return this.agentStatusField;
            }
            set {
                this.agentStatusField = value;
                this.RaisePropertyChanged("agentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string agentContactNumber {
            get {
                return this.agentContactNumberField;
            }
            set {
                this.agentContactNumberField = value;
                this.RaisePropertyChanged("agentContactNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string designationCode {
            get {
                return this.designationCodeField;
            }
            set {
                this.designationCodeField = value;
                this.RaisePropertyChanged("designationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string genderCode {
            get {
                return this.genderCodeField;
            }
            set {
                this.genderCodeField = value;
                this.RaisePropertyChanged("genderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string agentUnit {
            get {
                return this.agentUnitField;
            }
            set {
                this.agentUnitField = value;
                this.RaisePropertyChanged("agentUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ulipStatus {
            get {
                return this.ulipStatusField;
            }
            set {
                this.ulipStatusField = value;
                this.RaisePropertyChanged("ulipStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.futuregenerali.in/life/LFAgentServiceBPMIntf")]
    public partial class getAgentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LF_AgentDetail agentDetailField;
        
        private LF_ExceptionDetail faultResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public LF_AgentDetail agentDetail {
            get {
                return this.agentDetailField;
            }
            set {
                this.agentDetailField = value;
                this.RaisePropertyChanged("agentDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public LF_ExceptionDetail faultResponse {
            get {
                return this.faultResponseField;
            }
            set {
                this.faultResponseField = value;
                this.RaisePropertyChanged("faultResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAgentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.futuregenerali.in/life/LFAgentServiceBPMIntf", Order=0)]
        public UWSaralServices.LAAgentEnquiry.getAgent getAgent;
        
        public getAgentRequest() {
        }
        
        public getAgentRequest(UWSaralServices.LAAgentEnquiry.getAgent getAgent) {
            this.getAgent = getAgent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAgentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.futuregenerali.in/life/LFAgentServiceBPMIntf", Order=0)]
        public UWSaralServices.LAAgentEnquiry.getAgentResponse getAgentResponse;
        
        public getAgentResponse1() {
        }
        
        public getAgentResponse1(UWSaralServices.LAAgentEnquiry.getAgentResponse getAgentResponse) {
            this.getAgentResponse = getAgentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LFAgentServiceBPMIntfChannel : UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LFAgentServiceBPMIntfClient : System.ServiceModel.ClientBase<UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf>, UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf {
        
        public LFAgentServiceBPMIntfClient() {
        }
        
        public LFAgentServiceBPMIntfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LFAgentServiceBPMIntfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LFAgentServiceBPMIntfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LFAgentServiceBPMIntfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UWSaralServices.LAAgentEnquiry.getAgentResponse1 UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf.getAgent(UWSaralServices.LAAgentEnquiry.getAgentRequest request) {
            return base.Channel.getAgent(request);
        }
        
        public UWSaralServices.LAAgentEnquiry.getAgentResponse getAgent(UWSaralServices.LAAgentEnquiry.getAgent getAgent1) {
            UWSaralServices.LAAgentEnquiry.getAgentRequest inValue = new UWSaralServices.LAAgentEnquiry.getAgentRequest();
            inValue.getAgent = getAgent1;
            UWSaralServices.LAAgentEnquiry.getAgentResponse1 retVal = ((UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf)(this)).getAgent(inValue);
            return retVal.getAgentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWSaralServices.LAAgentEnquiry.getAgentResponse1> UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf.getAgentAsync(UWSaralServices.LAAgentEnquiry.getAgentRequest request) {
            return base.Channel.getAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAAgentEnquiry.getAgentResponse1> getAgentAsync(UWSaralServices.LAAgentEnquiry.getAgent getAgent) {
            UWSaralServices.LAAgentEnquiry.getAgentRequest inValue = new UWSaralServices.LAAgentEnquiry.getAgentRequest();
            inValue.getAgent = getAgent;
            return ((UWSaralServices.LAAgentEnquiry.LFAgentServiceBPMIntf)(this)).getAgentAsync(inValue);
        }
    }
}
