//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.AFICFI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Master : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORCODE {
            get {
                return this.ERRORCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORCODEField, value) != true)) {
                    this.ERRORCODEField = value;
                    this.RaisePropertyChanged("ERRORCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUES {
            get {
                return this.VALUESField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUESField, value) != true)) {
                    this.VALUESField = value;
                    this.RaisePropertyChanged("VALUES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AFICFI.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CONAFI", ReplyAction="http://tempuri.org/IService/CONAFIResponse")]
        UWSaralServices.AFICFI.Master CONAFI(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CONAFI", ReplyAction="http://tempuri.org/IService/CONAFIResponse")]
        System.Threading.Tasks.Task<UWSaralServices.AFICFI.Master> CONAFIAsync(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CONCFI", ReplyAction="http://tempuri.org/IService/CONCFIResponse")]
        UWSaralServices.AFICFI.Master CONCFI(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CONCFI", ReplyAction="http://tempuri.org/IService/CONCFIResponse")]
        System.Threading.Tasks.Task<UWSaralServices.AFICFI.Master> CONCFIAsync(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UWSaralServices.AFICFI.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UWSaralServices.AFICFI.IService>, UWSaralServices.AFICFI.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.AFICFI.Master CONAFI(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CONAFI(CHDRSEL, REASONCD, RESNDESC, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.AFICFI.Master> CONAFIAsync(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CONAFIAsync(CHDRSEL, REASONCD, RESNDESC, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public UWSaralServices.AFICFI.Master CONCFI(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CONCFI(CHDRSEL, REASONCD, RESNDESC, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.AFICFI.Master> CONCFIAsync(string CHDRSEL, string REASONCD, string RESNDESC, string Branch, string UserRole, string UserID, string PartnerID, string ProcessID, string ApplicationNo) {
            return base.Channel.CONCFIAsync(CHDRSEL, REASONCD, RESNDESC, Branch, UserRole, UserID, PartnerID, ProcessID, ApplicationNo);
        }
    }
}
