//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralSchedulerTPA.TiffServiceConsume {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TiffServiceConsume.TiffConverterServiceSoap")]
    public interface TiffConverterServiceSoap {
        
        // CODEGEN: Generating message contract since element name strFileExtension from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTiffBytes", ReplyAction="*")]
        UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse GetTiffBytes(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTiffBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse> GetTiffBytesAsync(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiffBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiffBytes", Namespace="http://tempuri.org/", Order=0)]
        public UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequestBody Body;
        
        public GetTiffBytesRequest() {
        }
        
        public GetTiffBytesRequest(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTiffBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFileExtension;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] arrFileBytes;
        
        public GetTiffBytesRequestBody() {
        }
        
        public GetTiffBytesRequestBody(string strFileExtension, byte[] arrFileBytes) {
            this.strFileExtension = strFileExtension;
            this.arrFileBytes = arrFileBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiffBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiffBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponseBody Body;
        
        public GetTiffBytesResponse() {
        }
        
        public GetTiffBytesResponse(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTiffBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytesResult;
        
        public GetTiffBytesResponseBody() {
        }
        
        public GetTiffBytesResponseBody(UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytesResult) {
            this.GetTiffBytesResult = GetTiffBytesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiffConverterServiceSoapChannel : UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiffConverterServiceSoapClient : System.ServiceModel.ClientBase<UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap>, UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap {
        
        public TiffConverterServiceSoapClient() {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiffConverterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiffConverterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap.GetTiffBytes(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest request) {
            return base.Channel.GetTiffBytes(request);
        }
        
        public UWSaralServices.LAServiceTiffConversion.ResponseData GetTiffBytes(string strFileExtension, byte[] arrFileBytes) {
            UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest inValue = new UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest();
            inValue.Body = new UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequestBody();
            inValue.Body.strFileExtension = strFileExtension;
            inValue.Body.arrFileBytes = arrFileBytes;
            UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse retVal = ((UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap)(this)).GetTiffBytes(inValue);
            return retVal.Body.GetTiffBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse> UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap.GetTiffBytesAsync(UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest request) {
            return base.Channel.GetTiffBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesResponse> GetTiffBytesAsync(string strFileExtension, byte[] arrFileBytes) {
            UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest inValue = new UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequest();
            inValue.Body = new UWSaralSchedulerTPA.TiffServiceConsume.GetTiffBytesRequestBody();
            inValue.Body.strFileExtension = strFileExtension;
            inValue.Body.arrFileBytes = arrFileBytes;
            return ((UWSaralSchedulerTPA.TiffServiceConsume.TiffConverterServiceSoap)(this)).GetTiffBytesAsync(inValue);
        }
    }
}
