//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LAPremiumCalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifeAssuredEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class LifeAssuredEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonCoverTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmokerStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonCoverType {
            get {
                return this.PersonCoverTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonCoverTypeField, value) != true)) {
                    this.PersonCoverTypeField = value;
                    this.RaisePropertyChanged("PersonCoverType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmokerStatus {
            get {
                return this.SmokerStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SmokerStatusField, value) != true)) {
                    this.SmokerStatusField = value;
                    this.RaisePropertyChanged("SmokerStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProposerEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class ProposerEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class ProductEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CashBackPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentType {
            get {
                return this.AgentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentTypeField, value) != true)) {
                    this.AgentTypeField = value;
                    this.RaisePropertyChanged("AgentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CashBackPeriod {
            get {
                return this.CashBackPeriodField;
            }
            set {
                if ((this.CashBackPeriodField.Equals(value) != true)) {
                    this.CashBackPeriodField = value;
                    this.RaisePropertyChanged("CashBackPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class PolicyEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AccrualPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodOfPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolicyTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PremiumPaymentTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumofReceiptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ULIPAmountReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AccrualPeriod {
            get {
                return this.AccrualPeriodField;
            }
            set {
                if ((this.AccrualPeriodField.Equals(value) != true)) {
                    this.AccrualPeriodField = value;
                    this.RaisePropertyChanged("AccrualPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStaff {
            get {
                return this.IsStaffField;
            }
            set {
                if ((this.IsStaffField.Equals(value) != true)) {
                    this.IsStaffField = value;
                    this.RaisePropertyChanged("IsStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodOfPayment {
            get {
                return this.MethodOfPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodOfPaymentField, value) != true)) {
                    this.MethodOfPaymentField = value;
                    this.RaisePropertyChanged("MethodOfPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyTerm {
            get {
                return this.PolicyTermField;
            }
            set {
                if ((this.PolicyTermField.Equals(value) != true)) {
                    this.PolicyTermField = value;
                    this.RaisePropertyChanged("PolicyTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PremiumPaymentTerm {
            get {
                return this.PremiumPaymentTermField;
            }
            set {
                if ((this.PremiumPaymentTermField.Equals(value) != true)) {
                    this.PremiumPaymentTermField = value;
                    this.RaisePropertyChanged("PremiumPaymentTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumofReceipts {
            get {
                return this.SumofReceiptsField;
            }
            set {
                if ((this.SumofReceiptsField.Equals(value) != true)) {
                    this.SumofReceiptsField = value;
                    this.RaisePropertyChanged("SumofReceipts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ULIPAmountReceived {
            get {
                return this.ULIPAmountReceivedField;
            }
            set {
                if ((this.ULIPAmountReceivedField.Equals(value) != true)) {
                    this.ULIPAmountReceivedField = value;
                    this.RaisePropertyChanged("ULIPAmountReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class SystemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BusinessDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RiskCommencementDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BusinessDate {
            get {
                return this.BusinessDateField;
            }
            set {
                if ((this.BusinessDateField.Equals(value) != true)) {
                    this.BusinessDateField = value;
                    this.RaisePropertyChanged("BusinessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RiskCommencementDate {
            get {
                return this.RiskCommencementDateField;
            }
            set {
                if ((this.RiskCommencementDateField.Equals(value) != true)) {
                    this.RiskCommencementDateField = value;
                    this.RaisePropertyChanged("RiskCommencementDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RiderEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class RiderEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LifeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LoadingPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalLoadingClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NSAPFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NonMedicalLoadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RiderSumAssuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumAssuredAcrossPlansField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LifeType {
            get {
                return this.LifeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LifeTypeField, value) != true)) {
                    this.LifeTypeField = value;
                    this.RaisePropertyChanged("LifeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LoadingPercentage {
            get {
                return this.LoadingPercentageField;
            }
            set {
                if ((this.LoadingPercentageField.Equals(value) != true)) {
                    this.LoadingPercentageField = value;
                    this.RaisePropertyChanged("LoadingPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalLoadingClass {
            get {
                return this.MedicalLoadingClassField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicalLoadingClassField, value) != true)) {
                    this.MedicalLoadingClassField = value;
                    this.RaisePropertyChanged("MedicalLoadingClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NSAPFlag {
            get {
                return this.NSAPFlagField;
            }
            set {
                if ((this.NSAPFlagField.Equals(value) != true)) {
                    this.NSAPFlagField = value;
                    this.RaisePropertyChanged("NSAPFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NonMedicalLoading {
            get {
                return this.NonMedicalLoadingField;
            }
            set {
                if ((this.NonMedicalLoadingField.Equals(value) != true)) {
                    this.NonMedicalLoadingField = value;
                    this.RaisePropertyChanged("NonMedicalLoading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiderCode {
            get {
                return this.RiderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderCodeField, value) != true)) {
                    this.RiderCodeField = value;
                    this.RaisePropertyChanged("RiderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiderName {
            get {
                return this.RiderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderNameField, value) != true)) {
                    this.RiderNameField = value;
                    this.RaisePropertyChanged("RiderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RiderSumAssured {
            get {
                return this.RiderSumAssuredField;
            }
            set {
                if ((this.RiderSumAssuredField.Equals(value) != true)) {
                    this.RiderSumAssuredField = value;
                    this.RaisePropertyChanged("RiderSumAssured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumAssuredAcrossPlans {
            get {
                return this.SumAssuredAcrossPlansField;
            }
            set {
                if ((this.SumAssuredAcrossPlansField.Equals(value) != true)) {
                    this.SumAssuredAcrossPlansField = value;
                    this.RaisePropertyChanged("SumAssuredAcrossPlans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChildEntity", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class ChildEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChildDateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChildDateOfBirth {
            get {
                return this.ChildDateOfBirthField;
            }
            set {
                if ((this.ChildDateOfBirthField.Equals(value) != true)) {
                    this.ChildDateOfBirthField = value;
                    this.RaisePropertyChanged("ChildDateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayoutDetails", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class PayoutDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LumpSumPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayOutFrquencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayoutTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LumpSumPercent {
            get {
                return this.LumpSumPercentField;
            }
            set {
                if ((this.LumpSumPercentField.Equals(value) != true)) {
                    this.LumpSumPercentField = value;
                    this.RaisePropertyChanged("LumpSumPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayOutFrquency {
            get {
                return this.PayOutFrquencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PayOutFrquencyField, value) != true)) {
                    this.PayOutFrquencyField = value;
                    this.RaisePropertyChanged("PayOutFrquency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayoutTerm {
            get {
                return this.PayoutTermField;
            }
            set {
                if ((this.PayoutTermField.Equals(value) != true)) {
                    this.PayoutTermField = value;
                    this.RaisePropertyChanged("PayoutTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutType {
            get {
                return this.PayoutTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutTypeField, value) != true)) {
                    this.PayoutTypeField = value;
                    this.RaisePropertyChanged("PayoutType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifePremiumResult", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class LifePremiumResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AllowedSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BRErrMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BackdatedIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UWSaralServices.LAPremiumCalService.ComponentResults[] CompDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MODAL_PREM_TAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodOfPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TAX_MPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalInstalmentPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPremiumAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YouGetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YouPayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AllowedSA {
            get {
                return this.AllowedSAField;
            }
            set {
                if ((this.AllowedSAField.Equals(value) != true)) {
                    this.AllowedSAField = value;
                    this.RaisePropertyChanged("AllowedSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BRErrMessages {
            get {
                return this.BRErrMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.BRErrMessagesField, value) != true)) {
                    this.BRErrMessagesField = value;
                    this.RaisePropertyChanged("BRErrMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BackdatedInt {
            get {
                return this.BackdatedIntField;
            }
            set {
                if ((this.BackdatedIntField.Equals(value) != true)) {
                    this.BackdatedIntField = value;
                    this.RaisePropertyChanged("BackdatedInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UWSaralServices.LAPremiumCalService.ComponentResults[] CompDetail {
            get {
                return this.CompDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompDetailField, value) != true)) {
                    this.CompDetailField = value;
                    this.RaisePropertyChanged("CompDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MODAL_PREM_TAX {
            get {
                return this.MODAL_PREM_TAXField;
            }
            set {
                if ((this.MODAL_PREM_TAXField.Equals(value) != true)) {
                    this.MODAL_PREM_TAXField = value;
                    this.RaisePropertyChanged("MODAL_PREM_TAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodOfPayment {
            get {
                return this.MethodOfPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodOfPaymentField, value) != true)) {
                    this.MethodOfPaymentField = value;
                    this.RaisePropertyChanged("MethodOfPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TAX_MP {
            get {
                return this.TAX_MPField;
            }
            set {
                if ((this.TAX_MPField.Equals(value) != true)) {
                    this.TAX_MPField = value;
                    this.RaisePropertyChanged("TAX_MP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalInstalmentPremium {
            get {
                return this.TotalInstalmentPremiumField;
            }
            set {
                if ((this.TotalInstalmentPremiumField.Equals(value) != true)) {
                    this.TotalInstalmentPremiumField = value;
                    this.RaisePropertyChanged("TotalInstalmentPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPremiumAmount {
            get {
                return this.TotalPremiumAmountField;
            }
            set {
                if ((this.TotalPremiumAmountField.Equals(value) != true)) {
                    this.TotalPremiumAmountField = value;
                    this.RaisePropertyChanged("TotalPremiumAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double YouGet {
            get {
                return this.YouGetField;
            }
            set {
                if ((this.YouGetField.Equals(value) != true)) {
                    this.YouGetField = value;
                    this.RaisePropertyChanged("YouGet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double YouPay {
            get {
                return this.YouPayField;
            }
            set {
                if ((this.YouPayField.Equals(value) != true)) {
                    this.YouPayField = value;
                    this.RaisePropertyChanged("YouPay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComponentResults", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class ComponentResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComponentCdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EduCessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ExtraPremiumAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InstalmentPremiumAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LifeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MedicalLoadingPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MedicalLoadingRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ModalPremiumAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NonMedicalLoadingPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NonMedicalLoadingRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderCtgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RiderPPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RiderPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SeriveTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumAssuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumAssuredAcrossPlansField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentCd {
            get {
                return this.ComponentCdField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentCdField, value) != true)) {
                    this.ComponentCdField = value;
                    this.RaisePropertyChanged("ComponentCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EduCess {
            get {
                return this.EduCessField;
            }
            set {
                if ((this.EduCessField.Equals(value) != true)) {
                    this.EduCessField = value;
                    this.RaisePropertyChanged("EduCess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExtraPremiumAmt {
            get {
                return this.ExtraPremiumAmtField;
            }
            set {
                if ((this.ExtraPremiumAmtField.Equals(value) != true)) {
                    this.ExtraPremiumAmtField = value;
                    this.RaisePropertyChanged("ExtraPremiumAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InstalmentPremiumAmt {
            get {
                return this.InstalmentPremiumAmtField;
            }
            set {
                if ((this.InstalmentPremiumAmtField.Equals(value) != true)) {
                    this.InstalmentPremiumAmtField = value;
                    this.RaisePropertyChanged("InstalmentPremiumAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LifeType {
            get {
                return this.LifeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LifeTypeField, value) != true)) {
                    this.LifeTypeField = value;
                    this.RaisePropertyChanged("LifeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MedicalLoadingPremium {
            get {
                return this.MedicalLoadingPremiumField;
            }
            set {
                if ((this.MedicalLoadingPremiumField.Equals(value) != true)) {
                    this.MedicalLoadingPremiumField = value;
                    this.RaisePropertyChanged("MedicalLoadingPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MedicalLoadingRate {
            get {
                return this.MedicalLoadingRateField;
            }
            set {
                if ((this.MedicalLoadingRateField.Equals(value) != true)) {
                    this.MedicalLoadingRateField = value;
                    this.RaisePropertyChanged("MedicalLoadingRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ModalPremiumAmt {
            get {
                return this.ModalPremiumAmtField;
            }
            set {
                if ((this.ModalPremiumAmtField.Equals(value) != true)) {
                    this.ModalPremiumAmtField = value;
                    this.RaisePropertyChanged("ModalPremiumAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NonMedicalLoadingPremium {
            get {
                return this.NonMedicalLoadingPremiumField;
            }
            set {
                if ((this.NonMedicalLoadingPremiumField.Equals(value) != true)) {
                    this.NonMedicalLoadingPremiumField = value;
                    this.RaisePropertyChanged("NonMedicalLoadingPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NonMedicalLoadingRate {
            get {
                return this.NonMedicalLoadingRateField;
            }
            set {
                if ((this.NonMedicalLoadingRateField.Equals(value) != true)) {
                    this.NonMedicalLoadingRateField = value;
                    this.RaisePropertyChanged("NonMedicalLoadingRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiderCtg {
            get {
                return this.RiderCtgField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderCtgField, value) != true)) {
                    this.RiderCtgField = value;
                    this.RaisePropertyChanged("RiderCtg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RiderPPT {
            get {
                return this.RiderPPTField;
            }
            set {
                if ((this.RiderPPTField.Equals(value) != true)) {
                    this.RiderPPTField = value;
                    this.RaisePropertyChanged("RiderPPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RiderPT {
            get {
                return this.RiderPTField;
            }
            set {
                if ((this.RiderPTField.Equals(value) != true)) {
                    this.RiderPTField = value;
                    this.RaisePropertyChanged("RiderPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SeriveTax {
            get {
                return this.SeriveTaxField;
            }
            set {
                if ((this.SeriveTaxField.Equals(value) != true)) {
                    this.SeriveTaxField = value;
                    this.RaisePropertyChanged("SeriveTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumAssured {
            get {
                return this.SumAssuredField;
            }
            set {
                if ((this.SumAssuredField.Equals(value) != true)) {
                    this.SumAssuredField = value;
                    this.RaisePropertyChanged("SumAssured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumAssuredAcrossPlans {
            get {
                return this.SumAssuredAcrossPlansField;
            }
            set {
                if ((this.SumAssuredAcrossPlansField.Equals(value) != true)) {
                    this.SumAssuredAcrossPlansField = value;
                    this.RaisePropertyChanged("SumAssuredAcrossPlans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PremiumCalculatorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Life")]
    [System.SerializableAttribute()]
    public partial class PremiumCalculatorFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAPremiumCalService.ILifePremiumCalculator")]
    public interface ILifePremiumCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifePremiumCalculator/CalculatePremium", ReplyAction="http://tempuri.org/ILifePremiumCalculator/CalculatePremiumResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UWSaralServices.LAPremiumCalService.PremiumCalculatorFaultException), Action="http://tempuri.org/ILifePremiumCalculator/CalculatePremiumPremiumCalculatorFaultE" +
            "xceptionFault", Name="PremiumCalculatorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Life")]
        UWSaralServices.LAPremiumCalService.LifePremiumResult CalculatePremium(UWSaralServices.LAPremiumCalService.LifeAssuredEntity enPolicyHolder, UWSaralServices.LAPremiumCalService.ProposerEntity enProposer, UWSaralServices.LAPremiumCalService.ProductEntity enProduct, UWSaralServices.LAPremiumCalService.PolicyEntity enPolicy, UWSaralServices.LAPremiumCalService.SystemEntity enSystem, UWSaralServices.LAPremiumCalService.RiderEntity[] enRider, UWSaralServices.LAPremiumCalService.ChildEntity enChildEntity, string ReverseCalculation, UWSaralServices.LAPremiumCalService.PayoutDetails PayOutDtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifePremiumCalculator/CalculatePremium", ReplyAction="http://tempuri.org/ILifePremiumCalculator/CalculatePremiumResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LAPremiumCalService.LifePremiumResult> CalculatePremiumAsync(UWSaralServices.LAPremiumCalService.LifeAssuredEntity enPolicyHolder, UWSaralServices.LAPremiumCalService.ProposerEntity enProposer, UWSaralServices.LAPremiumCalService.ProductEntity enProduct, UWSaralServices.LAPremiumCalService.PolicyEntity enPolicy, UWSaralServices.LAPremiumCalService.SystemEntity enSystem, UWSaralServices.LAPremiumCalService.RiderEntity[] enRider, UWSaralServices.LAPremiumCalService.ChildEntity enChildEntity, string ReverseCalculation, UWSaralServices.LAPremiumCalService.PayoutDetails PayOutDtl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILifePremiumCalculatorChannel : UWSaralServices.LAPremiumCalService.ILifePremiumCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LifePremiumCalculatorClient : System.ServiceModel.ClientBase<UWSaralServices.LAPremiumCalService.ILifePremiumCalculator>, UWSaralServices.LAPremiumCalService.ILifePremiumCalculator {
        
        public LifePremiumCalculatorClient() {
        }
        
        public LifePremiumCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LifePremiumCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifePremiumCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifePremiumCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UWSaralServices.LAPremiumCalService.LifePremiumResult CalculatePremium(UWSaralServices.LAPremiumCalService.LifeAssuredEntity enPolicyHolder, UWSaralServices.LAPremiumCalService.ProposerEntity enProposer, UWSaralServices.LAPremiumCalService.ProductEntity enProduct, UWSaralServices.LAPremiumCalService.PolicyEntity enPolicy, UWSaralServices.LAPremiumCalService.SystemEntity enSystem, UWSaralServices.LAPremiumCalService.RiderEntity[] enRider, UWSaralServices.LAPremiumCalService.ChildEntity enChildEntity, string ReverseCalculation, UWSaralServices.LAPremiumCalService.PayoutDetails PayOutDtl) {
            return base.Channel.CalculatePremium(enPolicyHolder, enProposer, enProduct, enPolicy, enSystem, enRider, enChildEntity, ReverseCalculation, PayOutDtl);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LAPremiumCalService.LifePremiumResult> CalculatePremiumAsync(UWSaralServices.LAPremiumCalService.LifeAssuredEntity enPolicyHolder, UWSaralServices.LAPremiumCalService.ProposerEntity enProposer, UWSaralServices.LAPremiumCalService.ProductEntity enProduct, UWSaralServices.LAPremiumCalService.PolicyEntity enPolicy, UWSaralServices.LAPremiumCalService.SystemEntity enSystem, UWSaralServices.LAPremiumCalService.RiderEntity[] enRider, UWSaralServices.LAPremiumCalService.ChildEntity enChildEntity, string ReverseCalculation, UWSaralServices.LAPremiumCalService.PayoutDetails PayOutDtl) {
            return base.Channel.CalculatePremiumAsync(enPolicyHolder, enProposer, enProduct, enPolicy, enSystem, enRider, enChildEntity, ReverseCalculation, PayOutDtl);
        }
    }
}
