//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralSchedulerTPA.DMSDownload {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMSDownload.DMSDocumentDownloadService")]
    public interface DMSDocumentDownloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMSDocumentDownloadService/getDocfromDocList", ReplyAction="http://tempuri.org/DMSDocumentDownloadService/getDocfromDocListResponse")]
        bool getDocfromDocList(string AppId, string DocType, string filepath, string AppName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMSDocumentDownloadService/getDocfromDocList", ReplyAction="http://tempuri.org/DMSDocumentDownloadService/getDocfromDocListResponse")]
        System.Threading.Tasks.Task<bool> getDocfromDocListAsync(string AppId, string DocType, string filepath, string AppName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMSDocumentDownloadService/getLatestDoc", ReplyAction="http://tempuri.org/DMSDocumentDownloadService/getLatestDocResponse")]
        bool getLatestDoc(string AppId, string DocType, string filepath, string AppName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMSDocumentDownloadService/getLatestDoc", ReplyAction="http://tempuri.org/DMSDocumentDownloadService/getLatestDocResponse")]
        System.Threading.Tasks.Task<bool> getLatestDocAsync(string AppId, string DocType, string filepath, string AppName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DMSDocumentDownloadServiceChannel : UWSaralSchedulerTPA.DMSDownload.DMSDocumentDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMSDocumentDownloadServiceClient : System.ServiceModel.ClientBase<UWSaralSchedulerTPA.DMSDownload.DMSDocumentDownloadService>, UWSaralSchedulerTPA.DMSDownload.DMSDocumentDownloadService {
        
        public DMSDocumentDownloadServiceClient() {
        }
        
        public DMSDocumentDownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMSDocumentDownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMSDocumentDownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMSDocumentDownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool getDocfromDocList(string AppId, string DocType, string filepath, string AppName) {
            return base.Channel.getDocfromDocList(AppId, DocType, filepath, AppName);
        }
        
        public System.Threading.Tasks.Task<bool> getDocfromDocListAsync(string AppId, string DocType, string filepath, string AppName) {
            return base.Channel.getDocfromDocListAsync(AppId, DocType, filepath, AppName);
        }
        
        public bool getLatestDoc(string AppId, string DocType, string filepath, string AppName) {
            return base.Channel.getLatestDoc(AppId, DocType, filepath, AppName);
        }
        
        public System.Threading.Tasks.Task<bool> getLatestDocAsync(string AppId, string DocType, string filepath, string AppName) {
            return base.Channel.getLatestDocAsync(AppId, DocType, filepath, AppName);
        }
    }
}
